/**
 * System emoji database for the launcher's `:` prefix emoji picker mode.
 * Each entry is { e: "😀", n: "grinning face" }.
 */
var Emojis = [
    { e: "😀", n: "grinning face" },
    { e: "😃", n: "grinning face with big eyes" },
    { e: "😄", n: "grinning face with smiling eyes" },
    { e: "😁", n: "beaming face with smiling eyes" },
    { e: "😆", n: "grinning squinting face" },
    { e: "😅", n: "grinning face with sweat" },
    { e: "😂", n: "face with tears of joy" },
    { e: "🤣", n: "rolling on the floor laughing" },
    { e: "☺", n: "smiling face" },
    { e: "😊", n: "smiling face with smiling eyes" },
    { e: "😇", n: "smiling face with halo" },
    { e: "🙂", n: "slightly smiling face" },
    { e: "🙃", n: "upside-down face" },
    { e: "😉", n: "winking face" },
    { e: "😌", n: "relieved face" },
    { e: "🥲", n: "smiling face with tear" },
    { e: "😍", n: "smiling face with heart-eyes" },
    { e: "🥰", n: "smiling face with hearts" },
    { e: "😘", n: "face blowing a kiss" },
    { e: "😗", n: "kissing face" },
    { e: "😙", n: "kissing face with smiling eyes" },
    { e: "😚", n: "kissing face with closed eyes" },
    { e: "😋", n: "face savoring food" },
    { e: "😛", n: "face with tongue" },
    { e: "😝", n: "squinting face with tongue" },
    { e: "😜", n: "winking face with tongue" },
    { e: "🤪", n: "zany face" },
    { e: "🤨", n: "face with raised eyebrow" },
    { e: "🧐", n: "face with monocle" },
    { e: "🤓", n: "nerd face" },
    { e: "😎", n: "smiling face with sunglasses" },
    { e: "🤩", n: "star-struck" },
    { e: "🥳", n: "partying face" },
    { e: "😏", n: "smirking face" },
    { e: "😒", n: "unamused face" },
    { e: "😞", n: "disappointed face" },
    { e: "😔", n: "pensive face" },
    { e: "😟", n: "worried face" },
    { e: "😕", n: "confused face" },
    { e: "🙁", n: "slightly frowning face" },
    { e: "☹", n: "frowning face" },
    { e: "😣", n: "persevering face" },
    { e: "😖", n: "confounded face" },
    { e: "😫", n: "tired face" },
    { e: "😩", n: "weary face" },
    { e: "🥺", n: "pleading face" },
    { e: "😢", n: "crying face" },
    { e: "😭", n: "loudly crying face" },
    { e: "😤", n: "face with steam from nose" },
    { e: "😠", n: "angry face" },
    { e: "😡", n: "pouting face" },
    { e: "🤬", n: "face with symbols on mouth" },
    { e: "🤯", n: "exploding head" },
    { e: "😳", n: "flushed face" },
    { e: "🥵", n: "hot face" },
    { e: "🥶", n: "cold face" },
    { e: "😱", n: "face screaming in fear" },
    { e: "😨", n: "fearful face" },
    { e: "😰", n: "anxious face with sweat" },
    { e: "😥", n: "sad but relieved face" },
    { e: "😓", n: "downcast face with sweat" },
    { e: "🤗", n: "hugging face" },
    { e: "🤔", n: "thinking face" },
    { e: "🤭", n: "face with hand over mouth" },
    { e: "🥱", n: "yawning face" },
    { e: "🤫", n: "shushing face" },
    { e: "🤥", n: "lying face" },
    { e: "😶", n: "face without mouth" },
    { e: "😐", n: "neutral face" },
    { e: "😑", n: "expressionless face" },
    { e: "😬", n: "grimacing face" },
    { e: "🙄", n: "face with rolling eyes" },
    { e: "😯", n: "hushed face" },
    { e: "😦", n: "frowning face with open mouth" },
    { e: "😧", n: "anguished face" },
    { e: "😮", n: "face with open mouth" },
    { e: "😲", n: "astonished face" },
    { e: "😴", n: "sleeping face" },
    { e: "🤤", n: "drooling face" },
    { e: "😪", n: "sleepy face" },
    { e: "😵", n: "dizzy face" },
    { e: "🤐", n: "zipper-mouth face" },
    { e: "🥴", n: "woozy face" },
    { e: "🤢", n: "nauseated face" },
    { e: "🤮", n: "face vomiting" },
    { e: "🤧", n: "sneezing face" },
    { e: "😷", n: "face with medical mask" },
    { e: "🤒", n: "face with thermometer" },
    { e: "🤕", n: "face with head-bandage" },
    { e: "🤑", n: "money-mouth face" },
    { e: "🤠", n: "cowboy hat face" },
    { e: "🥸", n: "disguised face" },
    { e: "😈", n: "smiling face with horns" },
    { e: "👿", n: "angry face with horns" },
    { e: "👹", n: "ogre" },
    { e: "👺", n: "goblin" },
    { e: "🤡", n: "clown face" },
    { e: "💩", n: "pile of poo" },
    { e: "👻", n: "ghost" },
    { e: "💀", n: "skull" },
    { e: "☠", n: "skull and crossbones" },
    { e: "👽", n: "alien" },
    { e: "👾", n: "alien monster" },
    { e: "🤖", n: "robot" },
    { e: "🎃", n: "jack-o-lantern" },
    { e: "😺", n: "grinning cat" },
    { e: "😸", n: "grinning cat with smiling eyes" },
    { e: "😹", n: "cat with tears of joy" },
    { e: "😻", n: "smiling cat with heart-eyes" },
    { e: "😼", n: "cat with wry smile" },
    { e: "😽", n: "kissing cat" },
    { e: "🙀", n: "weary cat" },
    { e: "😿", n: "crying cat" },
    { e: "😾", n: "pouting cat" },
    { e: "🤲", n: "palms up together" },
    { e: "👐", n: "open hands" },
    { e: "🙌", n: "raising hands" },
    { e: "👏", n: "clapping hands" },
    { e: "🤝", n: "handshake" },
    { e: "👍", n: "thumbs up" },
    { e: "👎", n: "thumbs down" },
    { e: "👊", n: "oncoming fist" },
    { e: "✊", n: "raised fist" },
    { e: "🤛", n: "left-facing fist" },
    { e: "🤜", n: "right-facing fist" },
    { e: "🤞", n: "crossed fingers" },
    { e: "✌", n: "victory hand" },
    { e: "🤟", n: "love-you gesture" },
    { e: "🤘", n: "sign of the horns" },
    { e: "👌", n: "OK hand" },
    { e: "🤏", n: "pinching hand" },
    { e: "🤌", n: "pinched fingers" },
    { e: "👈", n: "backhand index pointing left" },
    { e: "👉", n: "backhand index pointing right" },
    { e: "👆", n: "backhand index pointing up" },
    { e: "👇", n: "backhand index pointing down" },
    { e: "☝", n: "index pointing up" },
    { e: "✋", n: "raised hand" },
    { e: "🤚", n: "raised back of hand" },
    { e: "🖐", n: "hand with fingers splayed" },
    { e: "🖖", n: "vulcan salute" },
    { e: "👋", n: "waving hand" },
    { e: "🤙", n: "call me hand" },
    { e: "💪", n: "flexed biceps" },
    { e: "🦾", n: "mechanical arm" },
    { e: "🖕", n: "middle finger" },
    { e: "✍", n: "writing hand" },
    { e: "🙏", n: "folded hands" },
    { e: "🦶", n: "foot" },
    { e: "🦵", n: "leg" },
    { e: "🦿", n: "mechanical leg" },
    { e: "💄", n: "lipstick" },
    { e: "💋", n: "kiss mark" },
    { e: "👄", n: "mouth" },
    { e: "🦷", n: "tooth" },
    { e: "👅", n: "tongue" },
    { e: "👂", n: "ear" },
    { e: "🦻", n: "ear with hearing aid" },
    { e: "👃", n: "nose" },
    { e: "👣", n: "footprints" },
    { e: "👁", n: "eye" },
    { e: "👀", n: "eyes" },
    { e: "🧠", n: "brain" },
    { e: "🫀", n: "anatomical heart" },
    { e: "🫁", n: "lungs" },
    { e: "🦴", n: "bone" },
    { e: "🗣", n: "speaking head" },
    { e: "👤", n: "bust in silhouette" },
    { e: "👥", n: "busts in silhouette" },
    { e: "🫂", n: "people hugging" },
    { e: "👶", n: "baby" },
    { e: "👧", n: "girl" },
    { e: "🧒", n: "child" },
    { e: "👦", n: "boy" },
    { e: "👩", n: "woman" },
    { e: "🧑", n: "person" },
    { e: "👨", n: "man" },
    { e: "👱", n: "person: blond hair" },
    { e: "🧔", n: "person: beard" },
    { e: "👵", n: "old woman" },
    { e: "🧓", n: "older person" },
    { e: "👴", n: "old man" },
    { e: "👲", n: "man with Chinese cap" },
    { e: "👳", n: "person wearing turban" },
    { e: "🧕", n: "woman with headscarf" },
    { e: "👮", n: "police officer" },
    { e: "👷", n: "construction worker" },
    { e: "💂", n: "guard" },
    { e: "🕵", n: "detective" },
    { e: "👰", n: "person with veil" },
    { e: "🤵", n: "person in tuxedo" },
    { e: "👸", n: "princess" },
    { e: "🤴", n: "prince" },
    { e: "🦸", n: "superhero" },
    { e: "🦹", n: "supervillain" },
    { e: "🥷", n: "ninja" },
    { e: "🤶", n: "Mrs. Claus" },
    { e: "🎅", n: "Santa Claus" },
    { e: "🧙", n: "mage" },
    { e: "🧝", n: "elf" },
    { e: "🧛", n: "vampire" },
    { e: "🧟", n: "zombie" },
    { e: "🧞", n: "genie" },
    { e: "🧜", n: "merperson" },
    { e: "🧚", n: "fairy" },
    { e: "👼", n: "baby angel" },
    { e: "🤰", n: "pregnant woman" },
    { e: "🤱", n: "breast-feeding" },
    { e: "🙇", n: "person bowing" },
    { e: "💁", n: "person tipping hand" },
    { e: "🙅", n: "person gesturing NO" },
    { e: "🙆", n: "person gesturing OK" },
    { e: "🙋", n: "person raising hand" },
    { e: "🧏", n: "deaf person" },
    { e: "🤦", n: "person facepalming" },
    { e: "🤷", n: "person shrugging" },
    { e: "🙎", n: "person pouting" },
    { e: "🙍", n: "person frowning" },
    { e: "💇", n: "person getting haircut" },
    { e: "💆", n: "person getting massage" },
    { e: "🧖", n: "person in steamy room" },
    { e: "💅", n: "nail polish" },
    { e: "🤳", n: "selfie" },
    { e: "💃", n: "woman dancing" },
    { e: "🕺", n: "man dancing" },
    { e: "👯", n: "people with bunny ears" },
    { e: "🕴", n: "man in suit levitating" },
    { e: "🚶", n: "person walking" },
    { e: "🧎", n: "person kneeling" },
    { e: "🏃", n: "person running" },
    { e: "🧍", n: "person standing" },
    { e: "👫", n: "woman and man holding hands" },
    { e: "👭", n: "women holding hands" },
    { e: "👬", n: "men holding hands" },
    { e: "💑", n: "couple with heart" },
    { e: "💏", n: "kiss" },
    { e: "👪", n: "family" },
    { e: "🧶", n: "yarn" },
    { e: "🧵", n: "thread" },
    { e: "🧥", n: "coat" },
    { e: "🥼", n: "lab coat" },
    { e: "🦺", n: "safety vest" },
    { e: "👚", n: "woman's clothes" },
    { e: "👕", n: "t-shirt" },
    { e: "👖", n: "jeans" },
    { e: "🩲", n: "briefs" },
    { e: "🩳", n: "shorts" },
    { e: "👔", n: "necktie" },
    { e: "👗", n: "dress" },
    { e: "👙", n: "bikini" },
    { e: "🩱", n: "one-piece swimsuit" },
    { e: "👘", n: "kimono" },
    { e: "🥻", n: "sari" },
    { e: "🥿", n: "flat shoe" },
    { e: "👠", n: "high-heeled shoe" },
    { e: "👡", n: "woman's sandal" },
    { e: "👢", n: "woman's boot" },
    { e: "👞", n: "man's shoe" },
    { e: "👟", n: "running shoe" },
    { e: "🥾", n: "hiking boot" },
    { e: "🩴", n: "thong sandal" },
    { e: "🧦", n: "socks" },
    { e: "🧤", n: "gloves" },
    { e: "🧣", n: "scarf" },
    { e: "🎩", n: "top hat" },
    { e: "🧢", n: "billed cap" },
    { e: "👒", n: "woman's hat" },
    { e: "🎓", n: "graduation cap" },
    { e: "⛑", n: "rescue worker's helmet" },
    { e: "🪖", n: "military helmet" },
    { e: "👑", n: "crown" },
    { e: "💍", n: "ring" },
    { e: "👝", n: "clutch bag" },
    { e: "👛", n: "purse" },
    { e: "👜", n: "handbag" },
    { e: "💼", n: "briefcase" },
    { e: "🎒", n: "backpack" },
    { e: "🧳", n: "luggage" },
    { e: "👓", n: "glasses" },
    { e: "🕶", n: "sunglasses" },
    { e: "🥽", n: "goggles" },
    { e: "🌂", n: "closed umbrella" },
    { e: "🦱", n: "curly hair" },
    { e: "🦰", n: "red hair" },
    { e: "🦳", n: "white hair" },
    { e: "🦲", n: "bald" },
    { e: "🐶", n: "dog face" },
    { e: "🐱", n: "cat face" },
    { e: "🐭", n: "mouse face" },
    { e: "🐹", n: "hamster" },
    { e: "🐰", n: "rabbit face" },
    { e: "🦊", n: "fox" },
    { e: "🐻", n: "bear" },
    { e: "🐼", n: "panda" },
    { e: "🐨", n: "koala" },
    { e: "🐯", n: "tiger face" },
    { e: "🦁", n: "lion" },
    { e: "🐮", n: "cow face" },
    { e: "🐷", n: "pig face" },
    { e: "🐽", n: "pig nose" },
    { e: "🐸", n: "frog" },
    { e: "🐵", n: "monkey face" },
    { e: "🙈", n: "see-no-evil monkey" },
    { e: "🙉", n: "hear-no-evil monkey" },
    { e: "🙊", n: "speak-no-evil monkey" },
    { e: "🐒", n: "monkey" },
    { e: "🐔", n: "chicken" },
    { e: "🐧", n: "penguin" },
    { e: "🐦", n: "bird" },
    { e: "🐤", n: "baby chick" },
    { e: "🐣", n: "hatching chick" },
    { e: "🐥", n: "front-facing baby chick" },
    { e: "🦆", n: "duck" },
    { e: "🦅", n: "eagle" },
    { e: "🦉", n: "owl" },
    { e: "🦇", n: "bat" },
    { e: "🐺", n: "wolf" },
    { e: "🐗", n: "boar" },
    { e: "🐴", n: "horse face" },
    { e: "🦄", n: "unicorn" },
    { e: "🐝", n: "honeybee" },
    { e: "🐛", n: "bug" },
    { e: "🦋", n: "butterfly" },
    { e: "🐌", n: "snail" },
    { e: "🐞", n: "lady beetle" },
    { e: "🐜", n: "ant" },
    { e: "🦟", n: "mosquito" },
    { e: "🦗", n: "cricket" },
    { e: "🕷", n: "spider" },
    { e: "🕸", n: "spider web" },
    { e: "🦂", n: "scorpion" },
    { e: "🐢", n: "turtle" },
    { e: "🐍", n: "snake" },
    { e: "🦎", n: "lizard" },
    { e: "🦖", n: "T-Rex" },
    { e: "🦕", n: "sauropod" },
    { e: "🐙", n: "octopus" },
    { e: "🦑", n: "squid" },
    { e: "🦐", n: "shrimp" },
    { e: "🦞", n: "lobster" },
    { e: "🐠", n: "tropical fish" },
    { e: "🐟", n: "fish" },
    { e: "🐡", n: "blowfish" },
    { e: "🦈", n: "shark" },
    { e: "🐬", n: "dolphin" },
    { e: "🐳", n: "spouting whale" },
    { e: "🐋", n: "whale" },
    { e: "🐊", n: "crocodile" },
    { e: "🐅", n: "tiger" },
    { e: "🐆", n: "leopard" },
    { e: "🦓", n: "zebra" },
    { e: "🦍", n: "gorilla" },
    { e: "🦧", n: "orangutan" },
    { e: "🐘", n: "elephant" },
    { e: "🦛", n: "hippopotamus" },
    { e: "🦏", n: "rhinoceros" },
    { e: "🐪", n: "camel" },
    { e: "🐫", n: "two-hump camel" },
    { e: "🦒", n: "giraffe" },
    { e: "🦘", n: "kangaroo" },
    { e: "🐃", n: "water buffalo" },
    { e: "🐂", n: "ox" },
    { e: "🐄", n: "cow" },
    { e: "🐎", n: "horse" },
    { e: "🐖", n: "pig" },
    { e: "🐏", n: "ram" },
    { e: "🐑", n: "ewe" },
    { e: "🦙", n: "llama" },
    { e: "🐐", n: "goat" },
    { e: "🦌", n: "deer" },
    { e: "🐕", n: "dog" },
    { e: "🐩", n: "poodle" },
    { e: "🦮", n: "guide dog" },
    { e: "🐕‍🦺", n: "service dog" },
    { e: "🐈", n: "cat" },
    { e: "🐓", n: "rooster" },
    { e: "🦃", n: "turkey" },
    { e: "🕊", n: "dove" },
    { e: "🐇", n: "rabbit" },
    { e: "🐁", n: "mouse" },
    { e: "🐀", n: "rat" },
    { e: "🐿", n: "chipmunk" },
    { e: "🦔", n: "hedgehog" },
    { e: "🍇", n: "grapes" },
    { e: "🍈", n: "melon" },
    { e: "🍉", n: "watermelon" },
    { e: "🍊", n: "tangerine" },
    { e: "🍋", n: "lemon" },
    { e: "🍌", n: "banana" },
    { e: "🍍", n: "pineapple" },
    { e: "🥭", n: "mango" },
    { e: "🍎", n: "red apple" },
    { e: "🍏", n: "green apple" },
    { e: "🍐", n: "pear" },
    { e: "🍑", n: "peach" },
    { e: "🍒", n: "cherries" },
    { e: "🍓", n: "strawberry" },
    { e: "🥝", n: "kiwi fruit" },
    { e: "🍅", n: "tomato" },
    { e: "🥥", n: "coconut" },
    { e: "🥑", n: "avocado" },
    { e: "🍆", n: "eggplant" },
    { e: "🥔", n: "potato" },
    { e: "🥕", n: "carrot" },
    { e: "🌽", n: "ear of corn" },
    { e: "🌶", n: "hot pepper" },
    { e: "🥒", n: "cucumber" },
    { e: "🥬", n: "leafy green" },
    { e: "🥦", n: "broccoli" },
    { e: "🧄", n: "garlic" },
    { e: "🧅", n: "onion" },
    { e: "🍄", n: "mushroom" },
    { e: "🥜", n: "peanuts" },
    { e: "🌰", n: "chestnut" },
    { e: "🍞", n: "bread" },
    { e: "🥐", n: "croissant" },
    { e: "🥖", n: "baguette bread" },
    { e: "🥨", n: "pretzel" },
    { e: "🥯", n: "bagel" },
    { e: "🥞", n: "pancakes" },
    { e: "🧇", n: "waffle" },
    { e: "🧀", n: "cheese wedge" },
    { e: "🍖", n: "meat on bone" },
    { e: "🍗", n: "poultry leg" },
    { e: "🥩", n: "cut of meat" },
    { e: "🥓", n: "bacon" },
    { e: "🍔", n: "hamburger" },
    { e: "🍟", n: "french fries" },
    { e: "🍕", n: "pizza" },
    { e: "🌭", n: "hot dog" },
    { e: "🥪", n: "sandwich" },
    { e: "🌮", n: "taco" },
    { e: "🌯", n: "burrito" },
    { e: "🥙", n: "stuffed flatbread" },
    { e: "🧆", n: "falafel" },
    { e: "🥚", n: "egg" },
    { e: "🍳", n: "cooking" },
    { e: "🥘", n: "shallow pan of food" },
    { e: "🍲", n: "pot of food" },
    { e: "🥣", n: "bowl with spoon" },
    { e: "🥗", n: "green salad" },
    { e: "🍿", n: "popcorn" },
    { e: "🧈", n: "butter" },
    { e: "🧂", n: "salt" },
    { e: "🥫", n: "canned food" },
    { e: "🍱", n: "bento box" },
    { e: "🍘", n: "rice cracker" },
    { e: "🍙", n: "rice ball" },
    { e: "🍚", n: "cooked rice" },
    { e: "🍛", n: "curry rice" },
    { e: "🍜", n: "steaming bowl" },
    { e: "🍝", n: "spaghetti" },
    { e: "🍠", n: "roasted sweet potato" },
    { e: "🍢", n: "oden" },
    { e: "🍣", n: "sushi" },
    { e: "🍤", n: "fried shrimp" },
    { e: "🍥", n: "fish cake with swirl" },
    { e: "🥮", n: "moon cake" },
    { e: "🍡", n: "dango" },
    { e: "🥟", n: "dumpling" },
    { e: "🥠", n: "fortune cookie" },
    { e: "🥡", n: "takeout box" },
    { e: "🦀", n: "crab" },
    { e: "🦞", n: "lobster" },
    { e: "🦐", n: "shrimp" },
    { e: "🦑", n: "squid" },
    { e: "🦪", n: "oyster" },
    { e: "🍦", n: "soft ice cream" },
    { e: "🍧", n: "shaved ice" },
    { e: "🍨", n: "ice cream" },
    { e: "🍩", n: "doughnut" },
    { e: "🍪", n: "cookie" },
    { e: "🎂", n: "birthday cake" },
    { e: "🍰", n: "shortcake" },
    { e: "🧁", n: "cupcake" },
    { e: "🥧", n: "pie" },
    { e: "🍫", n: "chocolate bar" },
    { e: "🍬", n: "candy" },
    { e: "🍭", n: "lollipop" },
    { e: "🍮", n: "custard" },
    { e: "🍯", n: "honey pot" },
    { e: "☕", n: "hot beverage" },
    { e: "🍵", n: "teacup without handle" },
    { e: "🍶", n: "sake" },
    { e: "🍾", n: "bottle with popping cork" },
    { e: "🍷", n: "wine glass" },
    { e: "🍸", n: "cocktail glass" },
    { e: "🍹", n: "tropical drink" },
    { e: "🍺", n: "beer mug" },
    { e: "🍻", n: "clinking beer mugs" },
    { e: "🥂", n: "clinking glasses" },
    { e: "🥃", n: "tumbler glass" },
    { e: "🥤", n: "cup with straw" },
    { e: "🧃", n: "beverage box" },
    { e: "🧉", n: "mate" },
    { e: "🧊", n: "ice" },
    { e: "🥢", n: "chopsticks" },
    { e: "🍽", n: "fork and knife with plate" },
    { e: "🍴", n: "fork and knife" },
    { e: "🥄", n: "spoon" },
    { e: "🔪", n: "kitchen knife" },
    { e: "🏺", n: "amphora" },
    { e: "🌍", n: "globe showing Europe-Africa" },
    { e: "🌎", n: "globe showing Americas" },
    { e: "🌏", n: "globe showing Asia-Australia" },
    { e: "🌐", n: "globe with meridians" },
    { e: "🗺", n: "world map" },
    { e: "🗾", n: "map of Japan" },
    { e: "🧭", n: "compass" },
    { e: "🏔", n: "snow-capped mountain" },
    { e: "⛰", n: "mountain" },
    { e: "🌋", n: "volcano" },
    { e: "🗻", n: "mount fuji" },
    { e: "🏕", n: "camping" },
    { e: "🏖", n: "beach with umbrella" },
    { e: "🏜", n: "desert" },
    { e: "🏝", n: "desert island" },
    { e: "🏞", n: "national park" },
    { e: "🏟", n: "stadium" },
    { e: "🏛", n: "classical building" },
    { e: "🏗", n: "building construction" },
    { e: "🧱", n: "brick" },
    { e: "🏘", n: "houses" },
    { e: "🏚", n: "derelict house" },
    { e: "🏠", n: "house" },
    { e: "🏡", n: "house with garden" },
    { e: "🏢", n: "office building" },
    { e: "🏣", n: "Japanese post office" },
    { e: "🏤", n: "post office" },
    { e: "🏥", n: "hospital" },
    { e: "🏦", n: "bank" },
    { e: "🏨", n: "hotel" },
    { e: "🏩", n: "love hotel" },
    { e: "🏪", n: "convenience store" },
    { e: "🏫", n: "school" },
    { e: "🏬", n: "department store" },
    { e: "💒", n: "wedding" },
    { e: "💈", n: "barber pole" },
    { e: "🚂", n: "locomotive" },
    { e: "🚃", n: "railway car" },
    { e: "🚄", n: "high-speed train" },
    { e: "🚅", n: "bullet train" },
    { e: "🚆", n: "train" },
    { e: "🚇", n: "metro" },
    { e: "🚈", n: "light rail" },
    { e: "🚉", n: "station" },
    { e: "🚊", n: "tram" },
    { e: "🚝", n: "monorail" },
    { e: "🚞", n: "mountain railway" },
    { e: "🚋", n: "tram car" },
    { e: "🚌", n: "bus" },
    { e: "🚍", n: "oncoming bus" },
    { e: "🚎", n: "trolleybus" },
    { e: "🚐", n: "minibus" },
    { e: "🚑", n: "ambulance" },
    { e: "🚒", n: "fire engine" },
    { e: "🚓", n: "police car" },
    { e: "🚔", n: "oncoming police car" },
    { e: "🚕", n: "taxi" },
    { e: "🚖", n: "oncoming taxi" },
    { e: "🚗", n: "automobile" },
    { e: "🚘", n: "oncoming automobile" },
    { e: "🚙", n: "sport utility vehicle" },
    { e: "🚚", n: "delivery truck" },
    { e: "🚛", n: "articulated lorry" },
    { e: "🚜", n: "tractor" },
    { e: "🏎", n: "racing car" },
    { e: "🚲", n: "bicycle" },
    { e: "🛴", n: "kick scooter" },
    { e: "🛹", n: "skateboard" },
    { e: "🛵", n: "motor scooter" },
    { e: "🚏", n: "bus stop" },
    { e: "🛣", n: "motorway" },
    { e: "🛤", n: "railway track" },
    { e: "🛢", n: "oil drum" },
    { e: "⛽", n: "fuel pump" },
    { e: "🚨", n: "police car light" },
    { e: "🚥", n: "horizontal traffic light" },
    { e: "🚦", n: "vertical traffic light" },
    { e: "🛑", n: "stop sign" },
    { e: "🚧", n: "construction" },
    { e: "⚓", n: "anchor" },
    { e: "⛵", n: "sailboat" },
    { e: "🛶", n: "canoe" },
    { e: "🚤", n: "speedboat" },
    { e: "🛳", n: "passenger ship" },
    { e: "⛴", n: "ferry" },
    { e: "🛥", n: "motor boat" },
    { e: "🚢", n: "ship" },
    { e: "✈", n: "airplane" },
    { e: "🛩", n: "small airplane" },
    { e: "🛫", n: "airplane departure" },
    { e: "🛬", n: "airplane arrival" },
    { e: "🪂", n: "parachute" },
    { e: "💺", n: "seat" },
    { e: "🚁", n: "helicopter" },
    { e: "🚟", n: "suspension railway" },
    { e: "🚠", n: "mountain cableway" },
    { e: "🚡", n: "aerial tramway" },
    { e: "🛰", n: "satellite" },
    { e: "🚀", n: "rocket" },
    { e: "🛸", n: "flying saucer" },
    { e: "⌛", n: "hourglass done" },
    { e: "⏳", n: "hourglass not done" },
    { e: "⌚", n: "watch" },
    { e: "⏰", n: "alarm clock" },
    { e: "⏱", n: "stopwatch" },
    { e: "⏲", n: "timer clock" },
    { e: "🕰", n: "mantelpiece clock" },
    { e: "🕛", n: "twelve o'clock" },
    { e: "🌑", n: "new moon" },
    { e: "🌒", n: "waxing crescent moon" },
    { e: "🌓", n: "first quarter moon" },
    { e: "🌔", n: "waxing gibbous moon" },
    { e: "🌕", n: "full moon" },
    { e: "🌖", n: "waning gibbous moon" },
    { e: "🌗", n: "last quarter moon" },
    { e: "🌘", n: "waning crescent moon" },
    { e: "🌙", n: "crescent moon" },
    { e: "🌚", n: "new moon face" },
    { e: "🌛", n: "first quarter moon face" },
    { e: "🌜", n: "last quarter moon face" },
    { e: "☀", n: "sun" },
    { e: "🌝", n: "full moon face" },
    { e: "🌞", n: "sun with face" },
    { e: "🪐", n: "ringed planet" },
    { e: "⭐", n: "star" },
    { e: "🌟", n: "glowing star" },
    { e: "🌠", n: "shooting star" },
    { e: "🌌", n: "milky way" },
    { e: "☁", n: "cloud" },
    { e: "⛅", n: "sun behind cloud" },
    { e: "⛈", n: "cloud with lightning and rain" },
    { e: "🌤", n: "sun behind small cloud" },
    { e: "🌥", n: "sun behind large cloud" },
    { e: "🌦", n: "sun behind rain cloud" },
    { e: "🌧", n: "cloud with rain" },
    { e: "🌨", n: "cloud with snow" },
    { e: "🌩", n: "cloud with lightning" },
    { e: "🌪", n: "tornado" },
    { e: "🌫", n: "fog" },
    { e: "🌬", n: "wind face" },
    { e: "🌀", n: "cyclone" },
    { e: "🌈", n: "rainbow" },
    { e: "🌂", n: "closed umbrella" },
    { e: "☂", n: "umbrella" },
    { e: "☔", n: "umbrella with rain drops" },
    { e: "⛱", n: "umbrella on ground" },
    { e: "⚡", n: "high voltage" },
    { e: "❄", n: "snowflake" },
    { e: "☃", n: "snowman" },
    { e: "⛄", n: "snowman without snow" },
    { e: "☄", n: "comet" },
    { e: "🔥", n: "fire" },
    { e: "💧", n: "droplet" },
    { e: "🌊", n: "water wave" },
    { e: "🎄", n: "Christmas tree" },
    { e: "✨", n: "sparkles" },
    { e: "🎋", n: "tanabata tree" },
    { e: "🎍", n: "pine decoration" },
    { e: "🎎", n: "Japanese dolls" },
    { e: "🎏", n: "carp streamer" },
    { e: "🎐", n: "wind chime" },
    { e: "🎑", n: "moon viewing ceremony" },
    { e: "🧧", n: "red envelope" },
    { e: "🎀", n: "ribbon" },
    { e: "🎁", n: "wrapped gift" },
    { e: "🎗", n: "reminder ribbon" },
    { e: "🎟", n: "admission tickets" },
    { e: "🎫", n: "ticket" },
    { e: "🎖", n: "military medal" },
    { e: "🏆", n: "trophy" },
    { e: "🏅", n: "sports medal" },
    { e: "🥇", n: "1st place medal" },
    { e: "🥈", n: "2nd place medal" },
    { e: "🥉", n: "3rd place medal" },
    { e: "⚽", n: "soccer ball" },
    { e: "⚾", n: "baseball" },
    { e: "🥎", n: "softball" },
    { e: "🏀", n: "basketball" },
    { e: "🏐", n: "volleyball" },
    { e: "🏈", n: "american football" },
    { e: "🏉", n: "rugby football" },
    { e: "🎾", n: "tennis" },
    { e: "🥏", n: "flying disc" },
    { e: "🎳", n: "bowling" },
    { e: "🏏", n: "cricket game" },
    { e: "🏑", n: "field hockey" },
    { e: "🏒", n: "ice hockey" },
    { e: "🥍", n: "lacrosse" },
    { e: "🏓", n: "ping pong" },
    { e: "🏸", n: "badminton" },
    { e: "🥊", n: "boxing glove" },
    { e: "🥋", n: "martial arts uniform" },
    { e: "🥅", n: "goal net" },
    { e: "⛳", n: "flag in hole" },
    { e: "⛸", n: "ice skate" },
    { e: "🎣", n: "fishing pole" },
    { e: "🤿", n: "diving mask" },
    { e: "🎽", n: "running shirt" },
    { e: "🎿", n: "skis" },
    { e: "🛷", n: "sled" },
    { e: "🥌", n: "curling stone" },
    { e: "🎯", n: "direct hit" },
    { e: "🪀", n: "yo-yo" },
    { e: "🪁", n: "kite" },
    { e: "🎱", n: "pool 8 ball" },
    { e: "🔮", n: "crystal ball" },
    { e: "🎮", n: "video game" },
    { e: "🕹", n: "joystick" },
    { e: "🎰", n: "slot machine" },
    { e: "🎲", n: "game die" },
    { e: "🧩", n: "puzzle piece" },
    { e: "🧸", n: "teddy bear" },
    { e: "♠", n: "spade suit" },
    { e: "♥", n: "heart suit" },
    { e: "♦", n: "diamond suit" },
    { e: "♣", n: "club suit" },
    { e: "♟", n: "chess pawn" },
    { e: "🃏", n: "joker" },
    { e: "🀄", n: "mahjong red dragon" },
    { e: "🎴", n: "flower playing cards" },
    { e: "🎭", n: "performing arts" },
    { e: "🖼", n: "framed picture" },
    { e: "🎨", n: "artist palette" },
    { e: "🧵", n: "thread" },
    { e: "🧶", n: "yarn" },
    { e: "👓", n: "glasses" },
    { e: "🕶", n: "sunglasses" },
    { e: "🥽", n: "goggles" },
    { e: "🥼", n: "lab coat" },
    { e: "🦺", n: "safety vest" },
    { e: "👔", n: "necktie" },
    { e: "👕", n: "t-shirt" },
    { e: "👖", n: "jeans" },
    { e: "🧣", n: "scarf" },
    { e: "🧤", n: "gloves" },
    { e: "🧥", n: "coat" },
    { e: "🧦", n: "socks" },
    { e: "👗", n: "dress" },
    { e: "👘", n: "kimono" },
    { e: "🥻", n: "sari" },
    { e: "🩱", n: "one-piece swimsuit" },
    { e: "🩲", n: "briefs" },
    { e: "🩳", n: "shorts" },
    { e: "👙", n: "bikini" },
    { e: "👚", n: "woman's clothes" },
    { e: "👛", n: "purse" },
    { e: "👜", n: "handbag" },
    { e: "👝", n: "clutch bag" },
    { e: "🛍", n: "shopping bags" },
    { e: "🎒", n: "backpack" },
    { e: "👞", n: "man's shoe" },
    { e: "👟", n: "running shoe" },
    { e: "🥾", n: "hiking boot" },
    { e: "🥿", n: "flat shoe" },
    { e: "👠", n: "high-heeled shoe" },
    { e: "👡", n: "woman's sandal" },
    { e: "🩰", n: "ballet shoes" },
    { e: "👢", n: "woman's boot" },
    { e: "👑", n: "crown" },
    { e: "👒", n: "woman's hat" },
    { e: "🎩", n: "top hat" },
    { e: "🎓", n: "graduation cap" },
    { e: "🧢", n: "billed cap" },
    { e: "⛑", n: "rescue worker's helmet" },
    { e: "📿", n: "prayer beads" },
    { e: "💄", n: "lipstick" },
    { e: "💍", n: "ring" },
    { e: "💎", n: "gem stone" },
    { e: "🔇", n: "muted speaker" },
    { e: "🔈", n: "speaker low volume" },
    { e: "🔉", n: "speaker medium volume" },
    { e: "🔊", n: "speaker high volume" },
    { e: "📢", n: "loudspeaker" },
    { e: "📣", n: "megaphone" },
    { e: "📯", n: "postal horn" },
    { e: "🔔", n: "bell" },
    { e: "🔕", n: "bell with slash" },
    { e: "🎼", n: "musical score" },
    { e: "🎵", n: "musical note" },
    { e: "🎶", n: "musical notes" },
    { e: "🎙", n: "studio microphone" },
    { e: "🎚", n: "level slider" },
    { e: "🎛", n: "control knobs" },
    { e: "🎤", n: "microphone" },
    { e: "🎧", n: "headphone" },
    { e: "📻", n: "radio" },
    { e: "🎷", n: "saxophone" },
    { e: "🎸", n: "guitar" },
    { e: "🎹", n: "musical keyboard" },
    { e: "🎺", n: "trumpet" },
    { e: "🎻", n: "violin" },
    { e: "🪕", n: "banjo" },
    { e: "🥁", n: "drum" },
    { e: "📱", n: "mobile phone" },
    { e: "📲", n: "mobile phone with arrow" },
    { e: "☎", n: "telephone" },
    { e: "📞", n: "telephone receiver" },
    { e: "📟", n: "pager" },
    { e: "📠", n: "fax machine" },
    { e: "🔋", n: "battery" },
    { e: "🔌", n: "electric plug" },
    { e: "💻", n: "laptop" },
    { e: "🖥", n: "desktop computer" },
    { e: "🖨", n: "printer" },
    { e: "⌨", n: "keyboard" },
    { e: "🖱", n: "computer mouse" },
    { e: "🖲", n: "trackball" },
    { e: "💽", n: "computer disk" },
    { e: "💾", n: "floppy disk" },
    { e: "💿", n: "optical disk" },
    { e: "📀", n: "dvd" },
    { e: "🧮", n: "abacus" },
    { e: "🎥", n: "movie camera" },
    { e: "🎞", n: "film frames" },
    { e: "📽", n: "film projector" },
    { e: "🎬", n: "clapper board" },
    { e: "📺", n: "television" },
    { e: "📷", n: "camera" },
    { e: "📸", n: "camera with flash" },
    { e: "📹", n: "video camera" },
    { e: "📼", n: "videocassette" },
    { e: "🔍", n: "magnifying glass tilted left" },
    { e: "🔎", n: "magnifying glass tilted right" },
    { e: "🕯", n: "candle" },
    { e: "💡", n: "light bulb" },
    { e: "🔦", n: "flashlight" },
    { e: "🏮", n: "red paper lantern" },
    { e: "🪔", n: "diya lamp" },
    { e: "📔", n: "notebook with decorative cover" },
    { e: "📕", n: "closed book" },
    { e: "📖", n: "open book" },
    { e: "📗", n: "green book" },
    { e: "📘", n: "blue book" },
    { e: "📙", n: "orange book" },
    { e: "📚", n: "books" },
    { e: "📓", n: "notebook" },
    { e: "📒", n: "ledger" },
    { e: "📃", n: "page with curl" },
    { e: "📜", n: "scroll" },
    { e: "📄", n: "page facing up" },
    { e: "📰", n: "newspaper" },
    { e: "🗞", n: "rolled-up newspaper" },
    { e: "📑", n: "bookmark tabs" },
    { e: "🔖", n: "bookmark" },
    { e: "🏷", n: "label" },
    { e: "💰", n: "money bag" },
    { e: "💴", n: "yen banknote" },
    { e: "💵", n: "dollar banknote" },
    { e: "💶", n: "euro banknote" },
    { e: "💷", n: "pound banknote" },
    { e: "💸", n: "money with wings" },
    { e: "💳", n: "credit card" },
    { e: "🧾", n: "receipt" },
    { e: "💹", n: "chart increasing with yen" },
    { e: "✉", n: "envelope" },
    { e: "📧", n: "e-mail" },
    { e: "📨", n: "incoming envelope" },
    { e: "📩", n: "envelope with arrow" },
    { e: "📤", n: "outbox tray" },
    { e: "📥", n: "inbox tray" },
    { e: "📦", n: "package" },
    { e: "📫", n: "closed mailbox with raised flag" },
    { e: "📪", n: "closed mailbox with lowered flag" },
    { e: "📬", n: "open mailbox with raised flag" },
    { e: "📭", n: "open mailbox with lowered flag" },
    { e: "📮", n: "postbox" },
    { e: "🗳", n: "ballot box with ballot" },
    { e: "✏", n: "pencil" },
    { e: "✒", n: "black nib" },
    { e: "🖋", n: "fountain pen" },
    { e: "🖊", n: "pen" },
    { e: "🖌", n: "paintbrush" },
    { e: "🖍", n: "crayon" },
    { e: "📝", n: "memo" },
    { e: "💼", n: "briefcase" },
    { e: "📁", n: "file folder" },
    { e: "📂", n: "open file folder" },
    { e: "🗂", n: "card index dividers" },
    { e: "📅", n: "calendar" },
    { e: "📆", n: "tear-off calendar" },
    { e: "🗒", n: "spiral notepad" },
    { e: "🗓", n: "spiral calendar" },
    { e: "📇", n: "card index" },
    { e: "📈", n: "chart increasing" },
    { e: "📉", n: "chart decreasing" },
    { e: "📊", n: "bar chart" },
    { e: "📋", n: "clipboard" },
    { e: "📌", n: "pushpin" },
    { e: "📍", n: "round pushpin" },
    { e: "📎", n: "paperclip" },
    { e: "🖇", n: "linked paperclips" },
    { e: "📏", n: "straight ruler" },
    { e: "📐", n: "triangular ruler" },
    { e: "✂", n: "scissors" },
    { e: "🗃", n: "card file box" },
    { e: "🗄", n: "file cabinet" },
    { e: "🗑", n: "wastebasket" },
    { e: "🔒", n: "locked" },
    { e: "🔓", n: "unlocked" },
    { e: "🔏", n: "locked with pen" },
    { e: "🔐", n: "locked with key" },
    { e: "🔑", n: "key" },
    { e: "🗝", n: "old key" },
    { e: "🔨", n: "hammer" },
    { e: "🪓", n: "axe" },
    { e: "⛏", n: "pick" },
    { e: "⚒", n: "hammer and pick" },
    { e: "🛠", n: "hammer and wrench" },
    { e: "🗡", n: "dagger" },
    { e: "⚔", n: "crossed swords" },
    { e: "🔫", n: "pistol" },
    { e: "🏹", n: "bow and arrow" },
    { e: "🛡", n: "shield" },
    { e: "🔧", n: "wrench" },
    { e: "🔩", n: "nut and bolt" },
    { e: "⚙", n: "gear" },
    { e: "🗜", n: "clamp" },
    { e: "⚖", n: "balance scale" },
    { e: "🦯", n: "probing cane" },
    { e: "🔗", n: "link" },
    { e: "⛓", n: "chains" },
    { e: "🧰", n: "toolbox" },
    { e: "🧲", n: "magnet" },
    { e: "⚗", n: "alembic" },
    { e: "🧪", n: "test tube" },
    { e: "🧫", n: "petri dish" },
    { e: "🧬", n: "dna" },
    { e: "🔬", n: "microscope" },
    { e: "🔭", n: "telescope" },
    { e: "📡", n: "satellite antenna" },
    { e: "💉", n: "syringe" },
    { e: "🩸", n: "drop of blood" },
    { e: "💊", n: "pill" },
    { e: "🩹", n: "adhesive bandage" },
    { e: "🩺", n: "stethoscope" },
    { e: "🚪", n: "door" },
    { e: "🛏", n: "bed" },
    { e: "🛋", n: "couch and lamp" },
    { e: "🪑", n: "chair" },
    { e: "🚽", n: "toilet" },
    { e: "🚿", n: "shower" },
    { e: "🛁", n: "bathtub" },
    { e: "🪒", n: "razor" },
    { e: "🧴", n: "lotion bottle" },
    { e: "🧷", n: "safety pin" },
    { e: "🧹", n: "broom" },
    { e: "🧺", n: "basket" },
    { e: "🧻", n: "roll of paper" },
    { e: "🧼", n: "soap" },
    { e: "🧽", n: "sponge" },
    { e: "🧯", n: "fire extinguisher" },
    { e: "🛒", n: "shopping cart" },
    { e: "🚬", n: "cigarette" },
    { e: "⚰", n: "coffin" },
    { e: "⚱", n: "funeral urn" },
    { e: "🗿", n: "moai" },
    { e: "🏧", n: "ATM sign" },
    { e: "🚮", n: "litter in bin sign" },
    { e: "🚰", n: "potable water" },
    { e: "♿", n: "wheelchair symbol" },
    { e: "🚹", n: "men's room" },
    { e: "🚺", n: "women's room" },
    { e: "🚻", n: "restroom" },
    { e: "🚼", n: "baby symbol" },
    { e: "🚾", n: "water closet" },
    { e: "🛂", n: "passport control" },
    { e: "🛃", n: "customs" },
    { e: "🛄", n: "baggage claim" },
    { e: "🛅", n: "left luggage" },
    { e: "⚠", n: "warning" },
    { e: "🚸", n: "children crossing" },
    { e: "⛔", n: "no entry" },
    { e: "🚫", n: "prohibited" },
    { e: "🚳", n: "no bicycles" },
    { e: "🚭", n: "no smoking" },
    { e: "🚯", n: "no littering" },
    { e: "🚱", n: "non-potable water" },
    { e: "🚷", n: "no pedestrians" },
    { e: "📵", n: "no mobile phones" },
    { e: "🔞", n: "no one under eighteen" },
    { e: "☢", n: "radioactive" },
    { e: "☣", n: "biohazard" },
    { e: "⬆", n: "up arrow" },
    { e: "↗", n: "up-right arrow" },
    { e: "➡", n: "right arrow" },
    { e: "↘", n: "down-right arrow" },
    { e: "⬇", n: "down arrow" },
    { e: "↙", n: "down-left arrow" },
    { e: "⬅", n: "left arrow" },
    { e: "↖", n: "up-left arrow" },
    { e: "↕", n: "up-down arrow" },
    { e: "↔", n: "left-right arrow" },
    { e: "↩", n: "right arrow curving left" },
    { e: "↪", n: "left arrow curving right" },
    { e: "⤴", n: "right arrow curving up" },
    { e: "⤵", n: "right arrow curving down" },
    { e: "🔄", n: "counterclockwise arrows button" },
    { e: "🔃", n: "clockwise vertical arrows" },
    { e: "🔙", n: "BACK arrow" },
    { e: "🔚", n: "END arrow" },
    { e: "🔛", n: "ON! arrow" },
    { e: "🔜", n: "SOON arrow" },
    { e: "🔝", n: "TOP arrow" },
    { e: "🛐", n: "place of worship" },
    { e: "⚛", n: "atom symbol" },
    { e: "🕉", n: "om" },
    { e: "✡", n: "star of David" },
    { e: "☸", n: "wheel of dharma" },
    { e: "☯", n: "yin yang" },
    { e: "✝", n: "latin cross" },
    { e: "☦", n: "orthodox cross" },
    { e: "☪", n: "star and crescent" },
    { e: "☮", n: "peace symbol" },
    { e: "🕎", n: "menorah" },
    { e: "🔯", n: "dotted six-pointed star" },
    { e: "♈", n: "Aries" },
    { e: "♉", n: "Taurus" },
    { e: "♊", n: "Gemini" },
    { e: "♋", n: "Cancer" },
    { e: "♌", n: "Leo" },
    { e: "♍", n: "Virgo" },
    { e: "♎", n: "Libra" },
    { e: "♏", n: "Scorpio" },
    { e: "♐", n: "Sagittarius" },
    { e: "♑", n: "Capricorn" },
    { e: "♒", n: "Aquarius" },
    { e: "♓", n: "Pisces" },
    { e: "⛎", n: "Ophiuchus" },
    { e: "🔀", n: "shuffle tracks button" },
    { e: "🔁", n: "repeat button" },
    { e: "🔂", n: "repeat single button" },
    { e: "▶", n: "play button" },
    { e: "⏩", n: "fast-forward button" },
    { e: "⏭", n: "next track button" },
    { e: "⏯", n: "play or pause button" },
    { e: "◀", n: "reverse button" },
    { e: "⏪", n: "fast reverse button" },
    { e: "⏮", n: "last track button" },
    { e: "🔼", n: "upwards button" },
    { e: "⏫", n: "fast up button" },
    { e: "🔽", n: "downwards button" },
    { e: "⏬", n: "fast down button" },
    { e: "⏸", n: "pause button" },
    { e: "⏹", n: "stop button" },
    { e: "⏺", n: "record button" },
    { e: "⏏", n: "eject button" },
    { e: "🎦", n: "cinema" },
    { e: "🔅", n: "dim button" },
    { e: "🔆", n: "bright button" },
    { e: "📶", n: "antenna bars" },
    { e: "📳", n: "vibration mode" },
    { e: "📴", n: "mobile phone off" },
    { e: "♀", n: "female sign" },
    { e: "♂", n: "male sign" },
    { e: "✖", n: "multiply" },
    { e: "➕", n: "plus" },
    { e: "➖", n: "minus" },
    { e: "➗", n: "divide" },
    { e: "♾", n: "infinity" },
    { e: "‼", n: "double exclamation mark" },
    { e: "⁉", n: "exclamation question mark" },
    { e: "❓", n: "question mark" },
    { e: "❔", n: "white question mark" },
    { e: "❕", n: "white exclamation mark" },
    { e: "❗", n: "exclamation mark" },
    { e: "〰", n: "wavy dash" },
    { e: "💱", n: "currency exchange" },
    { e: "💲", n: "heavy dollar sign" },
    { e: "⚕", n: "medical symbol" },
    { e: "♻", n: "recycling symbol" },
    { e: "⚜", n: "fleur-de-lis" },
    { e: "🔱", n: "trident emblem" },
    { e: "📛", n: "name badge" },
    { e: "🔰", n: "Japanese symbol for beginner" },
    { e: "⭕", n: "hollow red circle" },
    { e: "✅", n: "check mark button" },
    { e: "☑", n: "check box with check" },
    { e: "✔", n: "check mark" },
    { e: "❌", n: "cross mark" },
    { e: "❎", n: "cross mark button" },
    { e: "➰", n: "curly loop" },
    { e: "➿", n: "double curly loop" },
    { e: "〽", n: "part alternation mark" },
    { e: "✳", n: "eight-spoked asterisk" },
    { e: "✴", n: "eight-pointed star" },
    { e: "❇", n: "sparkle" },
    { e: "©", n: "copyright" },
    { e: "®", n: "registered" },
    { e: "™", n: "trade mark" },
    { e: "#️⃣", n: "keycap: #" },
    { e: "*️⃣", n: "keycap: *" },
    { e: "0️⃣", n: "keycap: 0" },
    { e: "1️⃣", n: "keycap: 1" },
    { e: "2️⃣", n: "keycap: 2" },
    { e: "3️⃣", n: "keycap: 3" },
    { e: "4️⃣", n: "keycap: 4" },
    { e: "5️⃣", n: "keycap: 5" },
    { e: "6️⃣", n: "keycap: 6" },
    { e: "7️⃣", n: "keycap: 7" },
    { e: "8️⃣", n: "keycap: 8" },
    { e: "9️⃣", n: "keycap: 9" },
    { e: "🔟", n: "keycap: 10" },
    { e: "🔠", n: "INPUT LATIN UPPERCASE" },
    { e: "🔡", n: "INPUT LATIN LOWERCASE" },
    { e: "🔢", n: "INPUT NUMBERS" },
    { e: "🔣", n: "INPUT SYMBOLS" },
    { e: "🔤", n: "INPUT LATIN LETTERS" },
    { e: "🅰", n: "A button (blood type)" },
    { e: "🆎", n: "AB button (blood type)" },
    { e: "🅱", n: "B button (blood type)" },
    { e: "🆑", n: "CL button" },
    { e: "🆒", n: "COOL button" },
    { e: "🆓", n: "FREE button" },
    { e: "ℹ", n: "information" },
    { e: "🆔", n: "ID button" },
    { e: "Ⓜ", n: "circled M" },
    { e: "🆕", n: "NEW button" },
    { e: "🆖", n: "NG button" },
    { e: "🅾", n: "O button (blood type)" },
    { e: "🆗", n: "OK button" },
    { e: "🅿", n: "P button" },
    { e: "🆘", n: "SOS button" },
    { e: "🆙", n: "UP! button" },
    { e: "🆚", n: "VS button" },
    { e: "🈁", n: "Japanese \"here\" button" },
    { e: "🈂", n: "Japanese \"service charge\" button" },
    { e: "🈷", n: "Japanese \"monthly amount\" button" },
    { e: "🈶", n: "Japanese \"not free of charge\" button" },
    { e: "🈯", n: "Japanese \"reserved\" button" },
    { e: "🉐", n: "Japanese \"bargain\" button" },
    { e: "🈹", n: "Japanese \"discount\" button" },
    { e: "🈚", n: "Japanese \"free of charge\" button" },
    { e: "🈲", n: "Japanese \"prohibited\" button" },
    { e: "🉑", n: "Japanese \"acceptable\" button" },
    { e: "🈸", n: "Japanese \"application\" button" },
    { e: "🈴", n: "Japanese \"passing grade\" button" },
    { e: "🈳", n: "Japanese \"vacancy\" button" },
    { e: "㊗", n: "Japanese \"congratulations\" button" },
    { e: "㊙", n: "Japanese \"secret\" button" },
    { e: "🈺", n: "Japanese \"open for business\" button" },
    { e: "🈵", n: "Japanese \"no vacancy\" button" },
    { e: "🔴", n: "red circle" },
    { e: "🟠", n: "orange circle" },
    { e: "🟡", n: "yellow circle" },
    { e: "🟢", n: "green circle" },
    { e: "🔵", n: "blue circle" },
    { e: "🟣", n: "purple circle" },
    { e: "🟤", n: "brown circle" },
    { e: "⚫", n: "black circle" },
    { e: "⚪", n: "white circle" },
    { e: "🟥", n: "red square" },
    { e: "🟧", n: "orange square" },
    { e: "🟨", n: "yellow square" },
    { e: "🟩", n: "green square" },
    { e: "🟦", n: "blue square" },
    { e: "🟪", n: "purple square" },
    { e: "🟫", n: "brown square" },
    { e: "⬛", n: "black large square" },
    { e: "⬜", n: "white large square" },
    { e: "◼", n: "black medium square" },
    { e: "◻", n: "white medium square" },
    { e: "◾", n: "black medium-small square" },
    { e: "◽", n: "white medium-small square" },
    { e: "▪", n: "black small square" },
    { e: "▫", n: "white small square" },
    { e: "🔶", n: "large orange diamond" },
    { e: "🔷", n: "large blue diamond" },
    { e: "🔸", n: "small orange diamond" },
    { e: "🔹", n: "small blue diamond" },
    { e: "🔺", n: "red triangle pointed up" },
    { e: "🔻", n: "red triangle pointed down" },
    { e: "💠", n: "diamond with a dot" },
    { e: "🔘", n: "radio button" },
    { e: "🔳", n: "white square button" },
    { e: "🔲", n: "black square button" },
    { e: "🏁", n: "chequered flag" },
    { e: "🚩", n: "triangular flag" },
    { e: "🎌", n: "crossed flags" },
    { e: "🏴", n: "black flag" },
    { e: "🏳", n: "white flag" },
    { e: "💭", n: "thought balloon" },
    { e: "💤", n: "zzz" },
    { e: "💮", n: "white flower" },
    { e: "🈴", n: "Japanese \"passing grade\" button" },
    { e: "🈲", n: "Japanese \"prohibited\" button" },
    { e: "🉐", n: "Japanese \"bargain\" button" }
];
