/**
 * System emoji database — generated from /usr/share/ibus-typing-booster/data/emoji.json.gz
 * 1367 emojis. Re-run utils/launcher/gen_emojis.py to refresh.
 */
var Emojis = [
    { e: "🥇", n: "1st place medal" },
    { e: "🥈", n: "2nd place medal" },
    { e: "🥉", n: "3rd place medal" },
    { e: "🅰", n: "a button (blood type)" },
    { e: "🆎", n: "ab button (blood type)" },
    { e: "🧮", n: "abacus" },
    { e: "🪗", n: "accordion" },
    { e: "🩹", n: "adhesive bandage" },
    { e: "🎟", n: "admission tickets" },
    { e: "🚡", n: "aerial tramway" },
    { e: "✈", n: "airplane" },
    { e: "🛬", n: "airplane arrival" },
    { e: "🛫", n: "airplane departure" },
    { e: "⏰", n: "alarm clock" },
    { e: "⚗", n: "alembic" },
    { e: "👽", n: "alien" },
    { e: "👾", n: "alien monster" },
    { e: "🚑", n: "ambulance" },
    { e: "🏈", n: "american football" },
    { e: "🏺", n: "amphora" },
    { e: "🫀", n: "anatomical heart" },
    { e: "⚓", n: "anchor" },
    { e: "💢", n: "anger symbol" },
    { e: "😠", n: "angry face" },
    { e: "👿", n: "angry face with horns" },
    { e: "😧", n: "anguished face" },
    { e: "🐜", n: "ant" },
    { e: "📶", n: "antenna bars" },
    { e: "😰", n: "anxious face with sweat" },
    { e: "♒", n: "aquarius" },
    { e: "♈", n: "aries" },
    { e: "🚛", n: "articulated lorry" },
    { e: "🎨", n: "artist palette" },
    { e: "*", n: "asterisk" },
    { e: "😲", n: "astonished face" },
    { e: "🏧", n: "atm sign" },
    { e: "⚛", n: "atom symbol" },
    { e: "🛺", n: "auto rickshaw" },
    { e: "🚗", n: "automobile" },
    { e: "🥑", n: "avocado" },
    { e: "🪓", n: "axe" },
    { e: "🅱", n: "b button (blood type)" },
    { e: "👶", n: "baby" },
    { e: "👼", n: "baby angel" },
    { e: "🍼", n: "baby bottle" },
    { e: "🐤", n: "baby chick" },
    { e: "🚼", n: "baby symbol" },
    { e: "🔙", n: "back arrow" },
    { e: "👇", n: "backhand index pointing down" },
    { e: "👈", n: "backhand index pointing left" },
    { e: "👉", n: "backhand index pointing right" },
    { e: "👆", n: "backhand index pointing up" },
    { e: "🎒", n: "backpack" },
    { e: "🥓", n: "bacon" },
    { e: "🦡", n: "badger" },
    { e: "🏸", n: "badminton" },
    { e: "🥯", n: "bagel" },
    { e: "🛄", n: "baggage claim" },
    { e: "🥖", n: "baguette bread" },
    { e: "⚖", n: "balance scale" },
    { e: "🦲", n: "bald" },
    { e: "🩰", n: "ballet shoes" },
    { e: "🎈", n: "balloon" },
    { e: "🗳", n: "ballot box with ballot" },
    { e: "🍌", n: "banana" },
    { e: "🪕", n: "banjo" },
    { e: "🏦", n: "bank" },
    { e: "📊", n: "bar chart" },
    { e: "💈", n: "barber pole" },
    { e: "⚾", n: "baseball" },
    { e: "🧺", n: "basket" },
    { e: "🏀", n: "basketball" },
    { e: "🦇", n: "bat" },
    { e: "🛁", n: "bathtub" },
    { e: "🔋", n: "battery" },
    { e: "🏖", n: "beach with umbrella" },
    { e: "😁", n: "beaming face with smiling eyes" },
    { e: "🐻", n: "bear" },
    { e: "💓", n: "beating heart" },
    { e: "🦫", n: "beaver" },
    { e: "🛏", n: "bed" },
    { e: "🍺", n: "beer mug" },
    { e: "🪲", n: "beetle" },
    { e: "🔔", n: "bell" },
    { e: "🫑", n: "bell pepper" },
    { e: "🔕", n: "bell with slash" },
    { e: "🛎", n: "bellhop bell" },
    { e: "🍱", n: "bento box" },
    { e: "🧃", n: "beverage box" },
    { e: "🚲", n: "bicycle" },
    { e: "👙", n: "bikini" },
    { e: "🧢", n: "billed cap" },
    { e: "☣", n: "biohazard" },
    { e: "🐦", n: "bird" },
    { e: "🎂", n: "birthday cake" },
    { e: "🦬", n: "bison" },
    { e: "⚫", n: "black circle" },
    { e: "🏴", n: "black flag" },
    { e: "🖤", n: "black heart" },
    { e: "⬛", n: "black large square" },
    { e: "◼", n: "black medium square" },
    { e: "◾", n: "black medium-small square" },
    { e: "✒", n: "black nib" },
    { e: "▪", n: "black small square" },
    { e: "🔲", n: "black square button" },
    { e: "🌼", n: "blossom" },
    { e: "🐡", n: "blowfish" },
    { e: "📘", n: "blue book" },
    { e: "🔵", n: "blue circle" },
    { e: "💙", n: "blue heart" },
    { e: "🟦", n: "blue square" },
    { e: "🫐", n: "blueberries" },
    { e: "🐗", n: "boar" },
    { e: "💣", n: "bomb" },
    { e: "🦴", n: "bone" },
    { e: "🔖", n: "bookmark" },
    { e: "📑", n: "bookmark tabs" },
    { e: "📚", n: "books" },
    { e: "🪃", n: "boomerang" },
    { e: "🍾", n: "bottle with popping cork" },
    { e: "💐", n: "bouquet" },
    { e: "🏹", n: "bow and arrow" },
    { e: "🥣", n: "bowl with spoon" },
    { e: "🎳", n: "bowling" },
    { e: "🥊", n: "boxing glove" },
    { e: "👦", n: "boy" },
    { e: "🧠", n: "brain" },
    { e: "🍞", n: "bread" },
    { e: "🤱", n: "breast-feeding" },
    { e: "🧱", n: "brick" },
    { e: "🌉", n: "bridge at night" },
    { e: "💼", n: "briefcase" },
    { e: "🩲", n: "briefs" },
    { e: "🔆", n: "bright button" },
    { e: "🥦", n: "broccoli" },
    { e: "💔", n: "broken heart" },
    { e: "🧹", n: "broom" },
    { e: "🟤", n: "brown circle" },
    { e: "🤎", n: "brown heart" },
    { e: "🟫", n: "brown square" },
    { e: "🧋", n: "bubble tea" },
    { e: "🪣", n: "bucket" },
    { e: "🐛", n: "bug" },
    { e: "🏗", n: "building construction" },
    { e: "🚅", n: "bullet train" },
    { e: "🌯", n: "burrito" },
    { e: "🚌", n: "bus" },
    { e: "🚏", n: "bus stop" },
    { e: "👤", n: "bust in silhouette" },
    { e: "👥", n: "busts in silhouette" },
    { e: "🧈", n: "butter" },
    { e: "🦋", n: "butterfly" },
    { e: "🌵", n: "cactus" },
    { e: "📅", n: "calendar" },
    { e: "🤙", n: "call me hand" },
    { e: "🐪", n: "camel" },
    { e: "📷", n: "camera" },
    { e: "📸", n: "camera with flash" },
    { e: "🏕", n: "camping" },
    { e: "♋", n: "cancer" },
    { e: "🕯", n: "candle" },
    { e: "🍬", n: "candy" },
    { e: "🥫", n: "canned food" },
    { e: "🛶", n: "canoe" },
    { e: "♑", n: "capricorn" },
    { e: "🗃", n: "card file box" },
    { e: "📇", n: "card index" },
    { e: "🗂", n: "card index dividers" },
    { e: "🎠", n: "carousel horse" },
    { e: "🎏", n: "carp streamer" },
    { e: "🪚", n: "carpentry saw" },
    { e: "🥕", n: "carrot" },
    { e: "🏰", n: "castle" },
    { e: "🐈", n: "cat" },
    { e: "🐱", n: "cat face" },
    { e: "😹", n: "cat with tears of joy" },
    { e: "😼", n: "cat with wry smile" },
    { e: "⛓", n: "chains" },
    { e: "🪑", n: "chair" },
    { e: "📉", n: "chart decreasing" },
    { e: "📈", n: "chart increasing" },
    { e: "💹", n: "chart increasing with yen" },
    { e: "☑", n: "check box with check" },
    { e: "✔", n: "check mark" },
    { e: "✅", n: "check mark button" },
    { e: "🧀", n: "cheese wedge" },
    { e: "🏁", n: "chequered flag" },
    { e: "🍒", n: "cherries" },
    { e: "🌸", n: "cherry blossom" },
    { e: "♟", n: "chess pawn" },
    { e: "🌰", n: "chestnut" },
    { e: "🐔", n: "chicken" },
    { e: "🧒", n: "child" },
    { e: "🚸", n: "children crossing" },
    { e: "🐿", n: "chipmunk" },
    { e: "🍫", n: "chocolate bar" },
    { e: "🥢", n: "chopsticks" },
    { e: "🎄", n: "christmas tree" },
    { e: "⛪", n: "church" },
    { e: "🚬", n: "cigarette" },
    { e: "🎦", n: "cinema" },
    { e: "Ⓜ", n: "circled m" },
    { e: "🎪", n: "circus tent" },
    { e: "🏙", n: "cityscape" },
    { e: "🌆", n: "cityscape at dusk" },
    { e: "🆑", n: "cl button" },
    { e: "🗜", n: "clamp" },
    { e: "🎬", n: "clapper board" },
    { e: "👏", n: "clapping hands" },
    { e: "🏛", n: "classical building" },
    { e: "🍻", n: "clinking beer mugs" },
    { e: "🥂", n: "clinking glasses" },
    { e: "📋", n: "clipboard" },
    { e: "🔃", n: "clockwise vertical arrows" },
    { e: "📕", n: "closed book" },
    { e: "📪", n: "closed mailbox with lowered flag" },
    { e: "📫", n: "closed mailbox with raised flag" },
    { e: "🌂", n: "closed umbrella" },
    { e: "☁", n: "cloud" },
    { e: "🌩", n: "cloud with lightning" },
    { e: "⛈", n: "cloud with lightning and rain" },
    { e: "🌧", n: "cloud with rain" },
    { e: "🌨", n: "cloud with snow" },
    { e: "🤡", n: "clown face" },
    { e: "♣", n: "club suit" },
    { e: "👝", n: "clutch bag" },
    { e: "🧥", n: "coat" },
    { e: "🪳", n: "cockroach" },
    { e: "🍸", n: "cocktail glass" },
    { e: "🥥", n: "coconut" },
    { e: "⚰", n: "coffin" },
    { e: "🪙", n: "coin" },
    { e: "🥶", n: "cold face" },
    { e: "💥", n: "collision" },
    { e: "☄", n: "comet" },
    { e: "🧭", n: "compass" },
    { e: "💽", n: "computer disk" },
    { e: "🖱", n: "computer mouse" },
    { e: "🎊", n: "confetti ball" },
    { e: "😖", n: "confounded face" },
    { e: "😕", n: "confused face" },
    { e: "🚧", n: "construction" },
    { e: "👷", n: "construction worker" },
    { e: "🎛", n: "control knobs" },
    { e: "🏪", n: "convenience store" },
    { e: "🍚", n: "cooked rice" },
    { e: "🍪", n: "cookie" },
    { e: "🍳", n: "cooking" },
    { e: "🆒", n: "cool button" },
    { e: "©", n: "copyright" },
    { e: "🛋", n: "couch and lamp" },
    { e: "🔄", n: "counterclockwise arrows button" },
    { e: "💑", n: "couple with heart" },
    { e: "🐄", n: "cow" },
    { e: "🐮", n: "cow face" },
    { e: "🤠", n: "cowboy hat face" },
    { e: "🦀", n: "crab" },
    { e: "🖍", n: "crayon" },
    { e: "💳", n: "credit card" },
    { e: "🌙", n: "crescent moon" },
    { e: "🦗", n: "cricket" },
    { e: "🏏", n: "cricket game" },
    { e: "🐊", n: "crocodile" },
    { e: "🥐", n: "croissant" },
    { e: "❌", n: "cross mark" },
    { e: "❎", n: "cross mark button" },
    { e: "🤞", n: "crossed fingers" },
    { e: "🎌", n: "crossed flags" },
    { e: "⚔", n: "crossed swords" },
    { e: "👑", n: "crown" },
    { e: "😿", n: "crying cat" },
    { e: "😢", n: "crying face" },
    { e: "🔮", n: "crystal ball" },
    { e: "🥒", n: "cucumber" },
    { e: "🥤", n: "cup with straw" },
    { e: "🧁", n: "cupcake" },
    { e: "🥌", n: "curling stone" },
    { e: "🦱", n: "curly hair" },
    { e: "➰", n: "curly loop" },
    { e: "💱", n: "currency exchange" },
    { e: "🍛", n: "curry rice" },
    { e: "🍮", n: "custard" },
    { e: "🛃", n: "customs" },
    { e: "🥩", n: "cut of meat" },
    { e: "🌀", n: "cyclone" },
    { e: "🗡", n: "dagger" },
    { e: "🍡", n: "dango" },
    { e: "🏿", n: "dark skin tone" },
    { e: "💨", n: "dashing away" },
    { e: "🧏", n: "deaf person" },
    { e: "🌳", n: "deciduous tree" },
    { e: "🦌", n: "deer" },
    { e: "🚚", n: "delivery truck" },
    { e: "🏬", n: "department store" },
    { e: "🏚", n: "derelict house" },
    { e: "🏜", n: "desert" },
    { e: "🏝", n: "desert island" },
    { e: "🖥", n: "desktop computer" },
    { e: "🕵", n: "detective" },
    { e: "♦", n: "diamond suit" },
    { e: "💠", n: "diamond with a dot" },
    { e: "8", n: "digit eight" },
    { e: "5", n: "digit five" },
    { e: "4", n: "digit four" },
    { e: "9", n: "digit nine" },
    { e: "1", n: "digit one" },
    { e: "7", n: "digit seven" },
    { e: "6", n: "digit six" },
    { e: "3", n: "digit three" },
    { e: "2", n: "digit two" },
    { e: "0", n: "digit zero" },
    { e: "🔅", n: "dim button" },
    { e: "🎯", n: "direct hit" },
    { e: "😞", n: "disappointed face" },
    { e: "🥸", n: "disguised face" },
    { e: "🤿", n: "diving mask" },
    { e: "➗", n: "division sign" },
    { e: "🪔", n: "diya lamp" },
    { e: "💫", n: "dizzy" },
    { e: "😵", n: "dizzy face" },
    { e: "🧬", n: "dna" },
    { e: "🦤", n: "dodo" },
    { e: "🐕", n: "dog" },
    { e: "🐶", n: "dog face" },
    { e: "💵", n: "dollar banknote" },
    { e: "🐬", n: "dolphin" },
    { e: "🚪", n: "door" },
    { e: "🔯", n: "dotted six-pointed star" },
    { e: "➿", n: "double curly loop" },
    { e: "‼", n: "double exclamation mark" },
    { e: "🍩", n: "doughnut" },
    { e: "🕊", n: "dove" },
    { e: "⬇", n: "down arrow" },
    { e: "↙", n: "down-left arrow" },
    { e: "↘", n: "down-right arrow" },
    { e: "😓", n: "downcast face with sweat" },
    { e: "🔽", n: "downwards button" },
    { e: "🐉", n: "dragon" },
    { e: "🐲", n: "dragon face" },
    { e: "👗", n: "dress" },
    { e: "🤤", n: "drooling face" },
    { e: "🩸", n: "drop of blood" },
    { e: "💧", n: "droplet" },
    { e: "🥁", n: "drum" },
    { e: "🦆", n: "duck" },
    { e: "🥟", n: "dumpling" },
    { e: "📀", n: "dvd" },
    { e: "📧", n: "e-mail" },
    { e: "🦅", n: "eagle" },
    { e: "👂", n: "ear" },
    { e: "🌽", n: "ear of corn" },
    { e: "🦻", n: "ear with hearing aid" },
    { e: "🥚", n: "egg" },
    { e: "🍆", n: "eggplant" },
    { e: "🕗", n: "eight o’clock" },
    { e: "✴", n: "eight-pointed star" },
    { e: "✳", n: "eight-spoked asterisk" },
    { e: "🕣", n: "eight-thirty" },
    { e: "⏏", n: "eject button" },
    { e: "🔌", n: "electric plug" },
    { e: "🐘", n: "elephant" },
    { e: "🛗", n: "elevator" },
    { e: "🕚", n: "eleven o’clock" },
    { e: "🕦", n: "eleven-thirty" },
    { e: "🧝", n: "elf" },
    { e: "🔚", n: "end arrow" },
    { e: "✉", n: "envelope" },
    { e: "📩", n: "envelope with arrow" },
    { e: "💶", n: "euro banknote" },
    { e: "🌲", n: "evergreen tree" },
    { e: "🐑", n: "ewe" },
    { e: "❗", n: "exclamation mark" },
    { e: "⁉", n: "exclamation question mark" },
    { e: "🤯", n: "exploding head" },
    { e: "😑", n: "expressionless face" },
    { e: "👁", n: "eye" },
    { e: "👀", n: "eyes" },
    { e: "😘", n: "face blowing a kiss" },
    { e: "😋", n: "face savoring food" },
    { e: "😱", n: "face screaming in fear" },
    { e: "🤮", n: "face vomiting" },
    { e: "🤭", n: "face with hand over mouth" },
    { e: "🤕", n: "face with head-bandage" },
    { e: "😷", n: "face with medical mask" },
    { e: "🧐", n: "face with monocle" },
    { e: "😮", n: "face with open mouth" },
    { e: "🤨", n: "face with raised eyebrow" },
    { e: "🙄", n: "face with rolling eyes" },
    { e: "😤", n: "face with steam from nose" },
    { e: "🤬", n: "face with symbols on mouth" },
    { e: "😂", n: "face with tears of joy" },
    { e: "🤒", n: "face with thermometer" },
    { e: "😛", n: "face with tongue" },
    { e: "😶", n: "face without mouth" },
    { e: "🏭", n: "factory" },
    { e: "🧚", n: "fairy" },
    { e: "🧆", n: "falafel" },
    { e: "🍂", n: "fallen leaf" },
    { e: "👪", n: "family" },
    { e: "⏬", n: "fast down button" },
    { e: "⏪", n: "fast reverse button" },
    { e: "⏫", n: "fast up button" },
    { e: "⏩", n: "fast-forward button" },
    { e: "📠", n: "fax machine" },
    { e: "😨", n: "fearful face" },
    { e: "🪶", n: "feather" },
    { e: "♀", n: "female sign" },
    { e: "🎡", n: "ferris wheel" },
    { e: "⛴", n: "ferry" },
    { e: "🏑", n: "field hockey" },
    { e: "🗄", n: "file cabinet" },
    { e: "📁", n: "file folder" },
    { e: "🎞", n: "film frames" },
    { e: "📽", n: "film projector" },
    { e: "🔥", n: "fire" },
    { e: "🚒", n: "fire engine" },
    { e: "🧯", n: "fire extinguisher" },
    { e: "🧨", n: "firecracker" },
    { e: "🎆", n: "fireworks" },
    { e: "🌓", n: "first quarter moon" },
    { e: "🌛", n: "first quarter moon face" },
    { e: "🐟", n: "fish" },
    { e: "🍥", n: "fish cake with swirl" },
    { e: "🎣", n: "fishing pole" },
    { e: "🕔", n: "five o’clock" },
    { e: "🕠", n: "five-thirty" },
    { e: "⛳", n: "flag in hole" },
    { e: "🦩", n: "flamingo" },
    { e: "🔦", n: "flashlight" },
    { e: "🥿", n: "flat shoe" },
    { e: "🫓", n: "flatbread" },
    { e: "⚜", n: "fleur-de-lis" },
    { e: "💪", n: "flexed biceps" },
    { e: "💾", n: "floppy disk" },
    { e: "🎴", n: "flower playing cards" },
    { e: "😳", n: "flushed face" },
    { e: "🪰", n: "fly" },
    { e: "🥏", n: "flying disc" },
    { e: "🛸", n: "flying saucer" },
    { e: "🌫", n: "fog" },
    { e: "🌁", n: "foggy" },
    { e: "🙏", n: "folded hands" },
    { e: "🫕", n: "fondue" },
    { e: "🦶", n: "foot" },
    { e: "👣", n: "footprints" },
    { e: "🍴", n: "fork and knife" },
    { e: "🍽", n: "fork and knife with plate" },
    { e: "🥠", n: "fortune cookie" },
    { e: "⛲", n: "fountain" },
    { e: "🖋", n: "fountain pen" },
    { e: "🍀", n: "four leaf clover" },
    { e: "🕓", n: "four o’clock" },
    { e: "🕟", n: "four-thirty" },
    { e: "🦊", n: "fox" },
    { e: "🖼", n: "framed picture" },
    { e: "🆓", n: "free button" },
    { e: "🍟", n: "french fries" },
    { e: "🍤", n: "fried shrimp" },
    { e: "🐸", n: "frog" },
    { e: "🐥", n: "front-facing baby chick" },
    { e: "☹", n: "frowning face" },
    { e: "😦", n: "frowning face with open mouth" },
    { e: "⛽", n: "fuel pump" },
    { e: "🌕", n: "full moon" },
    { e: "🌝", n: "full moon face" },
    { e: "⚱", n: "funeral urn" },
    { e: "🎲", n: "game die" },
    { e: "🧄", n: "garlic" },
    { e: "⚙", n: "gear" },
    { e: "💎", n: "gem stone" },
    { e: "♊", n: "gemini" },
    { e: "🧞", n: "genie" },
    { e: "👻", n: "ghost" },
    { e: "🦒", n: "giraffe" },
    { e: "👧", n: "girl" },
    { e: "🥛", n: "glass of milk" },
    { e: "👓", n: "glasses" },
    { e: "🌎", n: "globe showing americas" },
    { e: "🌏", n: "globe showing asia-australia" },
    { e: "🌍", n: "globe showing europe-africa" },
    { e: "🌐", n: "globe with meridians" },
    { e: "🧤", n: "gloves" },
    { e: "🌟", n: "glowing star" },
    { e: "🥅", n: "goal net" },
    { e: "🐐", n: "goat" },
    { e: "👺", n: "goblin" },
    { e: "🥽", n: "goggles" },
    { e: "🦍", n: "gorilla" },
    { e: "🎓", n: "graduation cap" },
    { e: "🍇", n: "grapes" },
    { e: "🍏", n: "green apple" },
    { e: "📗", n: "green book" },
    { e: "🟢", n: "green circle" },
    { e: "💚", n: "green heart" },
    { e: "🥗", n: "green salad" },
    { e: "🟩", n: "green square" },
    { e: "😬", n: "grimacing face" },
    { e: "😺", n: "grinning cat" },
    { e: "😸", n: "grinning cat with smiling eyes" },
    { e: "😀", n: "grinning face" },
    { e: "😃", n: "grinning face with big eyes" },
    { e: "😄", n: "grinning face with smiling eyes" },
    { e: "😅", n: "grinning face with sweat" },
    { e: "😆", n: "grinning squinting face" },
    { e: "💗", n: "growing heart" },
    { e: "💂", n: "guard" },
    { e: "🦮", n: "guide dog" },
    { e: "🎸", n: "guitar" },
    { e: "🍔", n: "hamburger" },
    { e: "🔨", n: "hammer" },
    { e: "⚒", n: "hammer and pick" },
    { e: "🛠", n: "hammer and wrench" },
    { e: "🐹", n: "hamster" },
    { e: "🖐", n: "hand with fingers splayed" },
    { e: "👜", n: "handbag" },
    { e: "🤝", n: "handshake" },
    { e: "🐣", n: "hatching chick" },
    { e: "🎧", n: "headphone" },
    { e: "🪦", n: "headstone" },
    { e: "🙉", n: "hear-no-evil monkey" },
    { e: "💟", n: "heart decoration" },
    { e: "❣", n: "heart exclamation" },
    { e: "♥", n: "heart suit" },
    { e: "💘", n: "heart with arrow" },
    { e: "💝", n: "heart with ribbon" },
    { e: "💲", n: "heavy dollar sign" },
    { e: "🦔", n: "hedgehog" },
    { e: "🚁", n: "helicopter" },
    { e: "🌿", n: "herb" },
    { e: "🌺", n: "hibiscus" },
    { e: "⚡", n: "high voltage" },
    { e: "👠", n: "high-heeled shoe" },
    { e: "🚄", n: "high-speed train" },
    { e: "🥾", n: "hiking boot" },
    { e: "🛕", n: "hindu temple" },
    { e: "🦛", n: "hippopotamus" },
    { e: "🕳", n: "hole" },
    { e: "⭕", n: "hollow red circle" },
    { e: "🍯", n: "honey pot" },
    { e: "🐝", n: "honeybee" },
    { e: "🪝", n: "hook" },
    { e: "🚥", n: "horizontal traffic light" },
    { e: "🐎", n: "horse" },
    { e: "🐴", n: "horse face" },
    { e: "🏇", n: "horse racing" },
    { e: "🏥", n: "hospital" },
    { e: "☕", n: "hot beverage" },
    { e: "🌭", n: "hot dog" },
    { e: "🥵", n: "hot face" },
    { e: "🌶", n: "hot pepper" },
    { e: "♨", n: "hot springs" },
    { e: "🏨", n: "hotel" },
    { e: "⌛", n: "hourglass done" },
    { e: "⏳", n: "hourglass not done" },
    { e: "🏠", n: "house" },
    { e: "🏡", n: "house with garden" },
    { e: "🏘", n: "houses" },
    { e: "🤗", n: "hugging face" },
    { e: "💯", n: "hundred points" },
    { e: "😯", n: "hushed face" },
    { e: "🛖", n: "hut" },
    { e: "🍨", n: "ice cream" },
    { e: "🧊", n: "ice cube" },
    { e: "🏒", n: "ice hockey" },
    { e: "⛸", n: "ice skate" },
    { e: "🆔", n: "id button" },
    { e: "📥", n: "inbox tray" },
    { e: "📨", n: "incoming envelope" },
    { e: "☝", n: "index pointing up" },
    { e: "♾", n: "infinity" },
    { e: "ℹ", n: "information" },
    { e: "🔤", n: "input latin letters" },
    { e: "🔡", n: "input latin lowercase" },
    { e: "🔠", n: "input latin uppercase" },
    { e: "🔢", n: "input numbers" },
    { e: "🔣", n: "input symbols" },
    { e: "🎃", n: "jack-o-lantern" },
    { e: "🏯", n: "japanese castle" },
    { e: "🎎", n: "japanese dolls" },
    { e: "🏣", n: "japanese post office" },
    { e: "🔰", n: "japanese symbol for beginner" },
    { e: "🉑", n: "japanese “acceptable” button" },
    { e: "🈸", n: "japanese “application” button" },
    { e: "🉐", n: "japanese “bargain” button" },
    { e: "㊗", n: "japanese “congratulations” button" },
    { e: "🈹", n: "japanese “discount” button" },
    { e: "🈚", n: "japanese “free of charge” button" },
    { e: "🈁", n: "japanese “here” button" },
    { e: "🈷", n: "japanese “monthly amount” button" },
    { e: "🈵", n: "japanese “no vacancy” button" },
    { e: "🈶", n: "japanese “not free of charge” button" },
    { e: "🈺", n: "japanese “open for business” button" },
    { e: "🈴", n: "japanese “passing grade” button" },
    { e: "🈲", n: "japanese “prohibited” button" },
    { e: "🈯", n: "japanese “reserved” button" },
    { e: "㊙", n: "japanese “secret” button" },
    { e: "🈂", n: "japanese “service charge” button" },
    { e: "🈳", n: "japanese “vacancy” button" },
    { e: "👖", n: "jeans" },
    { e: "🃏", n: "joker" },
    { e: "🕹", n: "joystick" },
    { e: "🕋", n: "kaaba" },
    { e: "🦘", n: "kangaroo" },
    { e: "🔑", n: "key" },
    { e: "⌨", n: "keyboard" },
    { e: "🔟", n: "keycap: 10" },
    { e: "🛴", n: "kick scooter" },
    { e: "👘", n: "kimono" },
    { e: "💏", n: "kiss" },
    { e: "💋", n: "kiss mark" },
    { e: "😽", n: "kissing cat" },
    { e: "😗", n: "kissing face" },
    { e: "😚", n: "kissing face with closed eyes" },
    { e: "😙", n: "kissing face with smiling eyes" },
    { e: "🔪", n: "kitchen knife" },
    { e: "🪁", n: "kite" },
    { e: "🥝", n: "kiwi fruit" },
    { e: "🪢", n: "knot" },
    { e: "🐨", n: "koala" },
    { e: "🥼", n: "lab coat" },
    { e: "🏷", n: "label" },
    { e: "🥍", n: "lacrosse" },
    { e: "🪜", n: "ladder" },
    { e: "🐞", n: "lady beetle" },
    { e: "💻", n: "laptop computer" },
    { e: "🔷", n: "large blue diamond" },
    { e: "🔶", n: "large orange diamond" },
    { e: "🌗", n: "last quarter moon" },
    { e: "🌜", n: "last quarter moon face" },
    { e: "⏮", n: "last track button" },
    { e: "✝", n: "latin cross" },
    { e: "🍃", n: "leaf fluttering in wind" },
    { e: "🥬", n: "leafy green" },
    { e: "📒", n: "ledger" },
    { e: "⬅", n: "left arrow" },
    { e: "↪", n: "left arrow curving right" },
    { e: "🛅", n: "left luggage" },
    { e: "🗨", n: "left speech bubble" },
    { e: "🤛", n: "left-facing fist" },
    { e: "↔", n: "left-right arrow" },
    { e: "🦵", n: "leg" },
    { e: "🍋", n: "lemon" },
    { e: "♌", n: "leo" },
    { e: "🐆", n: "leopard" },
    { e: "🎚", n: "level slider" },
    { e: "♎", n: "libra" },
    { e: "💡", n: "light bulb" },
    { e: "🚈", n: "light rail" },
    { e: "🏻", n: "light skin tone" },
    { e: "🔗", n: "link" },
    { e: "🖇", n: "linked paperclips" },
    { e: "🦁", n: "lion" },
    { e: "💄", n: "lipstick" },
    { e: "🚮", n: "litter in bin sign" },
    { e: "🦎", n: "lizard" },
    { e: "🦙", n: "llama" },
    { e: "🦞", n: "lobster" },
    { e: "🔒", n: "locked" },
    { e: "🔐", n: "locked with key" },
    { e: "🔏", n: "locked with pen" },
    { e: "🚂", n: "locomotive" },
    { e: "🍭", n: "lollipop" },
    { e: "🪘", n: "long drum" },
    { e: "🧴", n: "lotion bottle" },
    { e: "😭", n: "loudly crying face" },
    { e: "📢", n: "loudspeaker" },
    { e: "🏩", n: "love hotel" },
    { e: "💌", n: "love letter" },
    { e: "🤟", n: "love-you gesture" },
    { e: "🧳", n: "luggage" },
    { e: "🫁", n: "lungs" },
    { e: "🤥", n: "lying face" },
    { e: "🧙", n: "mage" },
    { e: "🪄", n: "magic wand" },
    { e: "🧲", n: "magnet" },
    { e: "🔍", n: "magnifying glass tilted left" },
    { e: "🔎", n: "magnifying glass tilted right" },
    { e: "🀄", n: "mahjong red dragon" },
    { e: "♂", n: "male sign" },
    { e: "🦣", n: "mammoth" },
    { e: "👨", n: "man" },
    { e: "🕺", n: "man dancing" },
    { e: "🕴", n: "man in suit levitating" },
    { e: "👲", n: "man with chinese cap" },
    { e: "🥭", n: "mango" },
    { e: "🕰", n: "mantelpiece clock" },
    { e: "🦽", n: "manual wheelchair" },
    { e: "👞", n: "man’s shoe" },
    { e: "🗾", n: "map of japan" },
    { e: "🍁", n: "maple leaf" },
    { e: "🥋", n: "martial arts uniform" },
    { e: "🧉", n: "mate" },
    { e: "🍖", n: "meat on bone" },
    { e: "🦾", n: "mechanical arm" },
    { e: "🦿", n: "mechanical leg" },
    { e: "⚕", n: "medical symbol" },
    { e: "🏽", n: "medium skin tone" },
    { e: "🏾", n: "medium-dark skin tone" },
    { e: "🏼", n: "medium-light skin tone" },
    { e: "📣", n: "megaphone" },
    { e: "🍈", n: "melon" },
    { e: "📝", n: "memo" },
    { e: "👬", n: "men holding hands" },
    { e: "🕎", n: "menorah" },
    { e: "🚹", n: "men’s room" },
    { e: "🧜", n: "merperson" },
    { e: "🚇", n: "metro" },
    { e: "🦠", n: "microbe" },
    { e: "🎤", n: "microphone" },
    { e: "🔬", n: "microscope" },
    { e: "🖕", n: "middle finger" },
    { e: "🪖", n: "military helmet" },
    { e: "🎖", n: "military medal" },
    { e: "🌌", n: "milky way" },
    { e: "🚐", n: "minibus" },
    { e: "➖", n: "minus sign" },
    { e: "🪞", n: "mirror" },
    { e: "🗿", n: "moai" },
    { e: "📱", n: "mobile phone" },
    { e: "📴", n: "mobile phone off" },
    { e: "📲", n: "mobile phone with arrow" },
    { e: "💰", n: "money bag" },
    { e: "💸", n: "money with wings" },
    { e: "🤑", n: "money-mouth face" },
    { e: "🐒", n: "monkey" },
    { e: "🐵", n: "monkey face" },
    { e: "🚝", n: "monorail" },
    { e: "🥮", n: "moon cake" },
    { e: "🎑", n: "moon viewing ceremony" },
    { e: "🕌", n: "mosque" },
    { e: "🦟", n: "mosquito" },
    { e: "🛥", n: "motor boat" },
    { e: "🛵", n: "motor scooter" },
    { e: "🏍", n: "motorcycle" },
    { e: "🦼", n: "motorized wheelchair" },
    { e: "🛣", n: "motorway" },
    { e: "🗻", n: "mount fuji" },
    { e: "⛰", n: "mountain" },
    { e: "🚠", n: "mountain cableway" },
    { e: "🚞", n: "mountain railway" },
    { e: "🐁", n: "mouse" },
    { e: "🐭", n: "mouse face" },
    { e: "🪤", n: "mouse trap" },
    { e: "👄", n: "mouth" },
    { e: "🎥", n: "movie camera" },
    { e: "🤶", n: "mrs. claus" },
    { e: "✖", n: "multiplication sign" },
    { e: "🍄", n: "mushroom" },
    { e: "🎹", n: "musical keyboard" },
    { e: "🎵", n: "musical note" },
    { e: "🎶", n: "musical notes" },
    { e: "🎼", n: "musical score" },
    { e: "🔇", n: "muted speaker" },
    { e: "💅", n: "nail polish" },
    { e: "📛", n: "name badge" },
    { e: "🏞", n: "national park" },
    { e: "🤢", n: "nauseated face" },
    { e: "🧿", n: "nazar amulet" },
    { e: "👔", n: "necktie" },
    { e: "🤓", n: "nerd face" },
    { e: "🪆", n: "nesting dolls" },
    { e: "😐", n: "neutral face" },
    { e: "🆕", n: "new button" },
    { e: "🌑", n: "new moon" },
    { e: "🌚", n: "new moon face" },
    { e: "📰", n: "newspaper" },
    { e: "⏭", n: "next track button" },
    { e: "🆖", n: "ng button" },
    { e: "🌃", n: "night with stars" },
    { e: "🕘", n: "nine o’clock" },
    { e: "🕤", n: "nine-thirty" },
    { e: "🥷", n: "ninja" },
    { e: "🚳", n: "no bicycles" },
    { e: "⛔", n: "no entry" },
    { e: "🚯", n: "no littering" },
    { e: "📵", n: "no mobile phones" },
    { e: "🔞", n: "no one under eighteen" },
    { e: "🚷", n: "no pedestrians" },
    { e: "🚭", n: "no smoking" },
    { e: "🚱", n: "non-potable water" },
    { e: "👃", n: "nose" },
    { e: "📓", n: "notebook" },
    { e: "📔", n: "notebook with decorative cover" },
    { e: "🔩", n: "nut and bolt" },
    { e: "🅾", n: "o button (blood type)" },
    { e: "🐙", n: "octopus" },
    { e: "🍢", n: "oden" },
    { e: "🏢", n: "office building" },
    { e: "👹", n: "ogre" },
    { e: "🛢", n: "oil drum" },
    { e: "🆗", n: "ok button" },
    { e: "👌", n: "ok hand" },
    { e: "🗝", n: "old key" },
    { e: "👴", n: "old man" },
    { e: "👵", n: "old woman" },
    { e: "🧓", n: "older person" },
    { e: "🫒", n: "olive" },
    { e: "🕉", n: "om" },
    { e: "🔛", n: "on! arrow" },
    { e: "🚘", n: "oncoming automobile" },
    { e: "🚍", n: "oncoming bus" },
    { e: "👊", n: "oncoming fist" },
    { e: "🚔", n: "oncoming police car" },
    { e: "🚖", n: "oncoming taxi" },
    { e: "🕐", n: "one o’clock" },
    { e: "🩱", n: "one-piece swimsuit" },
    { e: "🕜", n: "one-thirty" },
    { e: "🧅", n: "onion" },
    { e: "📖", n: "open book" },
    { e: "📂", n: "open file folder" },
    { e: "👐", n: "open hands" },
    { e: "📭", n: "open mailbox with lowered flag" },
    { e: "📬", n: "open mailbox with raised flag" },
    { e: "⛎", n: "ophiuchus" },
    { e: "💿", n: "optical disk" },
    { e: "📙", n: "orange book" },
    { e: "🟠", n: "orange circle" },
    { e: "🧡", n: "orange heart" },
    { e: "🟧", n: "orange square" },
    { e: "🦧", n: "orangutan" },
    { e: "☦", n: "orthodox cross" },
    { e: "🦦", n: "otter" },
    { e: "📤", n: "outbox tray" },
    { e: "🦉", n: "owl" },
    { e: "🐂", n: "ox" },
    { e: "🦪", n: "oyster" },
    { e: "🅿", n: "p button" },
    { e: "📦", n: "package" },
    { e: "📄", n: "page facing up" },
    { e: "📃", n: "page with curl" },
    { e: "📟", n: "pager" },
    { e: "🖌", n: "paintbrush" },
    { e: "🌴", n: "palm tree" },
    { e: "🤲", n: "palms up together" },
    { e: "🥞", n: "pancakes" },
    { e: "🐼", n: "panda" },
    { e: "📎", n: "paperclip" },
    { e: "🪂", n: "parachute" },
    { e: "🦜", n: "parrot" },
    { e: "〽", n: "part alternation mark" },
    { e: "🎉", n: "party popper" },
    { e: "🥳", n: "partying face" },
    { e: "🛳", n: "passenger ship" },
    { e: "🛂", n: "passport control" },
    { e: "⏸", n: "pause button" },
    { e: "🐾", n: "paw prints" },
    { e: "☮", n: "peace symbol" },
    { e: "🍑", n: "peach" },
    { e: "🦚", n: "peacock" },
    { e: "🥜", n: "peanuts" },
    { e: "🍐", n: "pear" },
    { e: "🖊", n: "pen" },
    { e: "✏", n: "pencil" },
    { e: "🐧", n: "penguin" },
    { e: "😔", n: "pensive face" },
    { e: "🫂", n: "people hugging" },
    { e: "👯", n: "people with bunny ears" },
    { e: "🤼", n: "people wrestling" },
    { e: "🎭", n: "performing arts" },
    { e: "😣", n: "persevering face" },
    { e: "🧑", n: "person" },
    { e: "🚴", n: "person biking" },
    { e: "⛹", n: "person bouncing ball" },
    { e: "🙇", n: "person bowing" },
    { e: "🤸", n: "person cartwheeling" },
    { e: "🧗", n: "person climbing" },
    { e: "🤦", n: "person facepalming" },
    { e: "🤺", n: "person fencing" },
    { e: "🙍", n: "person frowning" },
    { e: "🙅", n: "person gesturing no" },
    { e: "🙆", n: "person gesturing ok" },
    { e: "💇", n: "person getting haircut" },
    { e: "💆", n: "person getting massage" },
    { e: "🏌", n: "person golfing" },
    { e: "🛌", n: "person in bed" },
    { e: "🧘", n: "person in lotus position" },
    { e: "🧖", n: "person in steamy room" },
    { e: "🤵", n: "person in tuxedo" },
    { e: "🤹", n: "person juggling" },
    { e: "🧎", n: "person kneeling" },
    { e: "🏋", n: "person lifting weights" },
    { e: "🚵", n: "person mountain biking" },
    { e: "🤾", n: "person playing handball" },
    { e: "🤽", n: "person playing water polo" },
    { e: "🙎", n: "person pouting" },
    { e: "🙋", n: "person raising hand" },
    { e: "🚣", n: "person rowing boat" },
    { e: "🏃", n: "person running" },
    { e: "🤷", n: "person shrugging" },
    { e: "🧍", n: "person standing" },
    { e: "🏄", n: "person surfing" },
    { e: "🏊", n: "person swimming" },
    { e: "🛀", n: "person taking bath" },
    { e: "💁", n: "person tipping hand" },
    { e: "🚶", n: "person walking" },
    { e: "👳", n: "person wearing turban" },
    { e: "👰", n: "person with veil" },
    { e: "🧔", n: "person: beard" },
    { e: "👱", n: "person: blond hair" },
    { e: "🧫", n: "petri dish" },
    { e: "⛏", n: "pick" },
    { e: "🛻", n: "pickup truck" },
    { e: "🥧", n: "pie" },
    { e: "🐖", n: "pig" },
    { e: "🐷", n: "pig face" },
    { e: "🐽", n: "pig nose" },
    { e: "💩", n: "pile of poo" },
    { e: "💊", n: "pill" },
    { e: "🤌", n: "pinched fingers" },
    { e: "🤏", n: "pinching hand" },
    { e: "🎍", n: "pine decoration" },
    { e: "🍍", n: "pineapple" },
    { e: "🏓", n: "ping pong" },
    { e: "♓", n: "pisces" },
    { e: "🔫", n: "pistol" },
    { e: "🍕", n: "pizza" },
    { e: "🪅", n: "piñata" },
    { e: "🪧", n: "placard" },
    { e: "🛐", n: "place of worship" },
    { e: "▶", n: "play button" },
    { e: "⏯", n: "play or pause button" },
    { e: "🥺", n: "pleading face" },
    { e: "🪠", n: "plunger" },
    { e: "➕", n: "plus sign" },
    { e: "🚓", n: "police car" },
    { e: "🚨", n: "police car light" },
    { e: "👮", n: "police officer" },
    { e: "🐩", n: "poodle" },
    { e: "🎱", n: "pool 8 ball" },
    { e: "🍿", n: "popcorn" },
    { e: "🏤", n: "post office" },
    { e: "📯", n: "postal horn" },
    { e: "📮", n: "postbox" },
    { e: "🍲", n: "pot of food" },
    { e: "🚰", n: "potable water" },
    { e: "🥔", n: "potato" },
    { e: "🪴", n: "potted plant" },
    { e: "🍗", n: "poultry leg" },
    { e: "💷", n: "pound banknote" },
    { e: "#", n: "pound symbol" },
    { e: "😾", n: "pouting cat" },
    { e: "😡", n: "pouting face" },
    { e: "📿", n: "prayer beads" },
    { e: "🤰", n: "pregnant woman" },
    { e: "🥨", n: "pretzel" },
    { e: "🤴", n: "prince" },
    { e: "👸", n: "princess" },
    { e: "🖨", n: "printer" },
    { e: "🦯", n: "probing cane" },
    { e: "🚫", n: "prohibited" },
    { e: "🟣", n: "purple circle" },
    { e: "💜", n: "purple heart" },
    { e: "🟪", n: "purple square" },
    { e: "👛", n: "purse" },
    { e: "📌", n: "pushpin" },
    { e: "🧩", n: "puzzle piece" },
    { e: "❓", n: "question mark" },
    { e: "🐇", n: "rabbit" },
    { e: "🐰", n: "rabbit face" },
    { e: "🦝", n: "raccoon" },
    { e: "🏎", n: "racing car" },
    { e: "📻", n: "radio" },
    { e: "🔘", n: "radio button" },
    { e: "☢", n: "radioactive" },
    { e: "🚃", n: "railway car" },
    { e: "🛤", n: "railway track" },
    { e: "🌈", n: "rainbow" },
    { e: "🤚", n: "raised back of hand" },
    { e: "✊", n: "raised fist" },
    { e: "✋", n: "raised hand" },
    { e: "🙌", n: "raising hands" },
    { e: "🐏", n: "ram" },
    { e: "🐀", n: "rat" },
    { e: "🪒", n: "razor" },
    { e: "🧾", n: "receipt" },
    { e: "⏺", n: "record button" },
    { e: "♻", n: "recycling symbol" },
    { e: "🍎", n: "red apple" },
    { e: "🔴", n: "red circle" },
    { e: "🧧", n: "red envelope" },
    { e: "🦰", n: "red hair" },
    { e: "❤", n: "red heart" },
    { e: "🏮", n: "red paper lantern" },
    { e: "🟥", n: "red square" },
    { e: "🔻", n: "red triangle pointed down" },
    { e: "🔺", n: "red triangle pointed up" },
    { e: "🇦", n: "regional indicator symbol letter a" },
    { e: "🇧", n: "regional indicator symbol letter b" },
    { e: "🇨", n: "regional indicator symbol letter c" },
    { e: "🇩", n: "regional indicator symbol letter d" },
    { e: "🇪", n: "regional indicator symbol letter e" },
    { e: "🇫", n: "regional indicator symbol letter f" },
    { e: "🇬", n: "regional indicator symbol letter g" },
    { e: "🇭", n: "regional indicator symbol letter h" },
    { e: "🇮", n: "regional indicator symbol letter i" },
    { e: "🇯", n: "regional indicator symbol letter j" },
    { e: "🇰", n: "regional indicator symbol letter k" },
    { e: "🇱", n: "regional indicator symbol letter l" },
    { e: "🇲", n: "regional indicator symbol letter m" },
    { e: "🇳", n: "regional indicator symbol letter n" },
    { e: "🇴", n: "regional indicator symbol letter o" },
    { e: "🇵", n: "regional indicator symbol letter p" },
    { e: "🇶", n: "regional indicator symbol letter q" },
    { e: "🇷", n: "regional indicator symbol letter r" },
    { e: "🇸", n: "regional indicator symbol letter s" },
    { e: "🇹", n: "regional indicator symbol letter t" },
    { e: "🇺", n: "regional indicator symbol letter u" },
    { e: "🇻", n: "regional indicator symbol letter v" },
    { e: "🇼", n: "regional indicator symbol letter w" },
    { e: "🇽", n: "regional indicator symbol letter x" },
    { e: "🇾", n: "regional indicator symbol letter y" },
    { e: "🇿", n: "regional indicator symbol letter z" },
    { e: "®", n: "registered" },
    { e: "😌", n: "relieved face" },
    { e: "🎗", n: "reminder ribbon" },
    { e: "🔁", n: "repeat button" },
    { e: "🔂", n: "repeat single button" },
    { e: "⛑", n: "rescue worker’s helmet" },
    { e: "🚻", n: "restroom" },
    { e: "◀", n: "reverse button" },
    { e: "💞", n: "revolving hearts" },
    { e: "🦏", n: "rhinoceros" },
    { e: "🎀", n: "ribbon" },
    { e: "🍙", n: "rice ball" },
    { e: "🍘", n: "rice cracker" },
    { e: "🗯", n: "right anger bubble" },
    { e: "➡", n: "right arrow" },
    { e: "⤵", n: "right arrow curving down" },
    { e: "↩", n: "right arrow curving left" },
    { e: "⤴", n: "right arrow curving up" },
    { e: "🤜", n: "right-facing fist" },
    { e: "💍", n: "ring" },
    { e: "🪐", n: "ringed planet" },
    { e: "🍠", n: "roasted sweet potato" },
    { e: "🤖", n: "robot" },
    { e: "🪨", n: "rock" },
    { e: "🚀", n: "rocket" },
    { e: "🧻", n: "roll of paper" },
    { e: "🗞", n: "rolled-up newspaper" },
    { e: "🎢", n: "roller coaster" },
    { e: "🛼", n: "roller skate" },
    { e: "🤣", n: "rolling on the floor laughing" },
    { e: "🐓", n: "rooster" },
    { e: "🌹", n: "rose" },
    { e: "🏵", n: "rosette" },
    { e: "📍", n: "round pushpin" },
    { e: "🏉", n: "rugby football" },
    { e: "🎽", n: "running shirt" },
    { e: "👟", n: "running shoe" },
    { e: "😥", n: "sad but relieved face" },
    { e: "🧷", n: "safety pin" },
    { e: "🦺", n: "safety vest" },
    { e: "♐", n: "sagittarius" },
    { e: "⛵", n: "sailboat" },
    { e: "🍶", n: "sake" },
    { e: "🧂", n: "salt" },
    { e: "🥪", n: "sandwich" },
    { e: "🎅", n: "santa claus" },
    { e: "🥻", n: "sari" },
    { e: "🛰", n: "satellite" },
    { e: "📡", n: "satellite antenna" },
    { e: "🦕", n: "sauropod" },
    { e: "🎷", n: "saxophone" },
    { e: "🧣", n: "scarf" },
    { e: "🏫", n: "school" },
    { e: "✂", n: "scissors" },
    { e: "♏", n: "scorpio" },
    { e: "🦂", n: "scorpion" },
    { e: "🪛", n: "screwdriver" },
    { e: "📜", n: "scroll" },
    { e: "🦭", n: "seal" },
    { e: "💺", n: "seat" },
    { e: "🙈", n: "see-no-evil monkey" },
    { e: "🌱", n: "seedling" },
    { e: "🤳", n: "selfie" },
    { e: "🕖", n: "seven o’clock" },
    { e: "🕢", n: "seven-thirty" },
    { e: "🪡", n: "sewing needle" },
    { e: "🥘", n: "shallow pan of food" },
    { e: "☘", n: "shamrock" },
    { e: "🦈", n: "shark" },
    { e: "🍧", n: "shaved ice" },
    { e: "🌾", n: "sheaf of rice" },
    { e: "🛡", n: "shield" },
    { e: "⛩", n: "shinto shrine" },
    { e: "🚢", n: "ship" },
    { e: "🌠", n: "shooting star" },
    { e: "🛍", n: "shopping bags" },
    { e: "🛒", n: "shopping cart" },
    { e: "🍰", n: "shortcake" },
    { e: "🩳", n: "shorts" },
    { e: "🚿", n: "shower" },
    { e: "🦐", n: "shrimp" },
    { e: "🔀", n: "shuffle tracks button" },
    { e: "🤫", n: "shushing face" },
    { e: "🤘", n: "sign of the horns" },
    { e: "🕕", n: "six o’clock" },
    { e: "🕡", n: "six-thirty" },
    { e: "🛹", n: "skateboard" },
    { e: "⛷", n: "skier" },
    { e: "🎿", n: "skis" },
    { e: "💀", n: "skull" },
    { e: "☠", n: "skull and crossbones" },
    { e: "🦨", n: "skunk" },
    { e: "🛷", n: "sled" },
    { e: "😴", n: "sleeping face" },
    { e: "😪", n: "sleepy face" },
    { e: "🙁", n: "slightly frowning face" },
    { e: "🙂", n: "slightly smiling face" },
    { e: "🎰", n: "slot machine" },
    { e: "🦥", n: "sloth" },
    { e: "🛩", n: "small airplane" },
    { e: "🔹", n: "small blue diamond" },
    { e: "🔸", n: "small orange diamond" },
    { e: "😻", n: "smiling cat with heart-eyes" },
    { e: "☺", n: "smiling face" },
    { e: "😇", n: "smiling face with halo" },
    { e: "😍", n: "smiling face with heart-eyes" },
    { e: "🥰", n: "smiling face with hearts" },
    { e: "😈", n: "smiling face with horns" },
    { e: "😊", n: "smiling face with smiling eyes" },
    { e: "😎", n: "smiling face with sunglasses" },
    { e: "🥲", n: "smiling face with tear" },
    { e: "😏", n: "smirking face" },
    { e: "🐌", n: "snail" },
    { e: "🐍", n: "snake" },
    { e: "🤧", n: "sneezing face" },
    { e: "🏔", n: "snow-capped mountain" },
    { e: "🏂", n: "snowboarder" },
    { e: "❄", n: "snowflake" },
    { e: "☃", n: "snowman" },
    { e: "⛄", n: "snowman without snow" },
    { e: "🧼", n: "soap" },
    { e: "⚽", n: "soccer ball" },
    { e: "🧦", n: "socks" },
    { e: "🍦", n: "soft ice cream" },
    { e: "🥎", n: "softball" },
    { e: "🔜", n: "soon arrow" },
    { e: "🆘", n: "sos button" },
    { e: "♠", n: "spade suit" },
    { e: "🍝", n: "spaghetti" },
    { e: "❇", n: "sparkle" },
    { e: "🎇", n: "sparkler" },
    { e: "✨", n: "sparkles" },
    { e: "💖", n: "sparkling heart" },
    { e: "🙊", n: "speak-no-evil monkey" },
    { e: "🔊", n: "speaker high volume" },
    { e: "🔈", n: "speaker low volume" },
    { e: "🔉", n: "speaker medium volume" },
    { e: "🗣", n: "speaking head" },
    { e: "💬", n: "speech balloon" },
    { e: "🚤", n: "speedboat" },
    { e: "🕷", n: "spider" },
    { e: "🕸", n: "spider web" },
    { e: "🗓", n: "spiral calendar" },
    { e: "🗒", n: "spiral notepad" },
    { e: "🐚", n: "spiral shell" },
    { e: "🧽", n: "sponge" },
    { e: "🥄", n: "spoon" },
    { e: "🚙", n: "sport utility vehicle" },
    { e: "🏅", n: "sports medal" },
    { e: "🐳", n: "spouting whale" },
    { e: "🦑", n: "squid" },
    { e: "😝", n: "squinting face with tongue" },
    { e: "🏟", n: "stadium" },
    { e: "⭐", n: "star" },
    { e: "☪", n: "star and crescent" },
    { e: "✡", n: "star of david" },
    { e: "🤩", n: "star-struck" },
    { e: "🚉", n: "station" },
    { e: "🗽", n: "statue of liberty" },
    { e: "🍜", n: "steaming bowl" },
    { e: "🩺", n: "stethoscope" },
    { e: "⏹", n: "stop button" },
    { e: "🛑", n: "stop sign" },
    { e: "⏱", n: "stopwatch" },
    { e: "📏", n: "straight ruler" },
    { e: "🍓", n: "strawberry" },
    { e: "🎙", n: "studio microphone" },
    { e: "🥙", n: "stuffed flatbread" },
    { e: "☀", n: "sun" },
    { e: "⛅", n: "sun behind cloud" },
    { e: "🌥", n: "sun behind large cloud" },
    { e: "🌦", n: "sun behind rain cloud" },
    { e: "🌤", n: "sun behind small cloud" },
    { e: "🌞", n: "sun with face" },
    { e: "🌻", n: "sunflower" },
    { e: "🕶", n: "sunglasses" },
    { e: "🌅", n: "sunrise" },
    { e: "🌄", n: "sunrise over mountains" },
    { e: "🌇", n: "sunset" },
    { e: "🦸", n: "superhero" },
    { e: "🦹", n: "supervillain" },
    { e: "🍣", n: "sushi" },
    { e: "🚟", n: "suspension railway" },
    { e: "🦢", n: "swan" },
    { e: "💦", n: "sweat droplets" },
    { e: "🕍", n: "synagogue" },
    { e: "💉", n: "syringe" },
    { e: "🦖", n: "t-rex" },
    { e: "👕", n: "t-shirt" },
    { e: "🌮", n: "taco" },
    { e: "🥡", n: "takeout box" },
    { e: "🫔", n: "tamale" },
    { e: "🎋", n: "tanabata tree" },
    { e: "🍊", n: "tangerine" },
    { e: "♉", n: "taurus" },
    { e: "🚕", n: "taxi" },
    { e: "🍵", n: "teacup without handle" },
    { e: "🫖", n: "teapot" },
    { e: "📆", n: "tear-off calendar" },
    { e: "🧸", n: "teddy bear" },
    { e: "☎", n: "telephone" },
    { e: "📞", n: "telephone receiver" },
    { e: "🔭", n: "telescope" },
    { e: "📺", n: "television" },
    { e: "🕙", n: "ten o’clock" },
    { e: "🕥", n: "ten-thirty" },
    { e: "🎾", n: "tennis" },
    { e: "⛺", n: "tent" },
    { e: "🧪", n: "test tube" },
    { e: "🌡", n: "thermometer" },
    { e: "🤔", n: "thinking face" },
    { e: "🩴", n: "thong sandal" },
    { e: "💭", n: "thought balloon" },
    { e: "🧵", n: "thread" },
    { e: "🕒", n: "three o’clock" },
    { e: "🕞", n: "three-thirty" },
    { e: "👎", n: "thumbs down" },
    { e: "👍", n: "thumbs up" },
    { e: "🎫", n: "ticket" },
    { e: "🐅", n: "tiger" },
    { e: "🐯", n: "tiger face" },
    { e: "⏲", n: "timer clock" },
    { e: "😫", n: "tired face" },
    { e: "🚽", n: "toilet" },
    { e: "🗼", n: "tokyo tower" },
    { e: "🍅", n: "tomato" },
    { e: "👅", n: "tongue" },
    { e: "🧰", n: "toolbox" },
    { e: "🦷", n: "tooth" },
    { e: "🪥", n: "toothbrush" },
    { e: "🔝", n: "top arrow" },
    { e: "🎩", n: "top hat" },
    { e: "🌪", n: "tornado" },
    { e: "🖲", n: "trackball" },
    { e: "🚜", n: "tractor" },
    { e: "™", n: "trade mark" },
    { e: "🚆", n: "train" },
    { e: "🚊", n: "tram" },
    { e: "🚋", n: "tram car" },
    { e: "⚧", n: "transgender symbol" },
    { e: "🚩", n: "triangular flag" },
    { e: "📐", n: "triangular ruler" },
    { e: "🔱", n: "trident emblem" },
    { e: "🚎", n: "trolleybus" },
    { e: "🏆", n: "trophy" },
    { e: "🍹", n: "tropical drink" },
    { e: "🐠", n: "tropical fish" },
    { e: "🎺", n: "trumpet" },
    { e: "🌷", n: "tulip" },
    { e: "🥃", n: "tumbler glass" },
    { e: "🦃", n: "turkey" },
    { e: "🐢", n: "turtle" },
    { e: "🕛", n: "twelve o’clock" },
    { e: "🕧", n: "twelve-thirty" },
    { e: "💕", n: "two hearts" },
    { e: "🕑", n: "two o’clock" },
    { e: "🐫", n: "two-hump camel" },
    { e: "🕝", n: "two-thirty" },
    { e: "☂", n: "umbrella" },
    { e: "⛱", n: "umbrella on ground" },
    { e: "☔", n: "umbrella with rain drops" },
    { e: "😒", n: "unamused face" },
    { e: "🦄", n: "unicorn" },
    { e: "🔓", n: "unlocked" },
    { e: "⬆", n: "up arrow" },
    { e: "🆙", n: "up! button" },
    { e: "↕", n: "up-down arrow" },
    { e: "↖", n: "up-left arrow" },
    { e: "↗", n: "up-right arrow" },
    { e: "🙃", n: "upside-down face" },
    { e: "🔼", n: "upwards button" },
    { e: "🧛", n: "vampire" },
    { e: "🚦", n: "vertical traffic light" },
    { e: "📳", n: "vibration mode" },
    { e: "✌", n: "victory hand" },
    { e: "📹", n: "video camera" },
    { e: "🎮", n: "video game" },
    { e: "📼", n: "videocassette" },
    { e: "🎻", n: "violin" },
    { e: "♍", n: "virgo" },
    { e: "🌋", n: "volcano" },
    { e: "🏐", n: "volleyball" },
    { e: "🆚", n: "vs button" },
    { e: "🖖", n: "vulcan salute" },
    { e: "🧇", n: "waffle" },
    { e: "🌘", n: "waning crescent moon" },
    { e: "🌖", n: "waning gibbous moon" },
    { e: "⚠", n: "warning" },
    { e: "🗑", n: "wastebasket" },
    { e: "⌚", n: "watch" },
    { e: "🐃", n: "water buffalo" },
    { e: "🚾", n: "water closet" },
    { e: "🌊", n: "water wave" },
    { e: "🍉", n: "watermelon" },
    { e: "👋", n: "waving hand" },
    { e: "〰", n: "wavy dash" },
    { e: "🌒", n: "waxing crescent moon" },
    { e: "🌔", n: "waxing gibbous moon" },
    { e: "🙀", n: "weary cat" },
    { e: "😩", n: "weary face" },
    { e: "💒", n: "wedding" },
    { e: "🐋", n: "whale" },
    { e: "☸", n: "wheel of dharma" },
    { e: "♿", n: "wheelchair symbol" },
    { e: "⚪", n: "white circle" },
    { e: "❕", n: "white exclamation mark" },
    { e: "🏳", n: "white flag" },
    { e: "💮", n: "white flower" },
    { e: "🦳", n: "white hair" },
    { e: "🤍", n: "white heart" },
    { e: "⬜", n: "white large square" },
    { e: "◻", n: "white medium square" },
    { e: "◽", n: "white medium-small square" },
    { e: "❔", n: "white question mark" },
    { e: "▫", n: "white small square" },
    { e: "🔳", n: "white square button" },
    { e: "🥀", n: "wilted flower" },
    { e: "🎐", n: "wind chime" },
    { e: "🌬", n: "wind face" },
    { e: "🪟", n: "window" },
    { e: "🍷", n: "wine glass" },
    { e: "😉", n: "winking face" },
    { e: "😜", n: "winking face with tongue" },
    { e: "🐺", n: "wolf" },
    { e: "👩", n: "woman" },
    { e: "👫", n: "woman and man holding hands" },
    { e: "💃", n: "woman dancing" },
    { e: "🧕", n: "woman with headscarf" },
    { e: "👢", n: "woman’s boot" },
    { e: "👚", n: "woman’s clothes" },
    { e: "👒", n: "woman’s hat" },
    { e: "👡", n: "woman’s sandal" },
    { e: "👭", n: "women holding hands" },
    { e: "🚺", n: "women’s room" },
    { e: "🪵", n: "wood" },
    { e: "🥴", n: "woozy face" },
    { e: "🗺", n: "world map" },
    { e: "🪱", n: "worm" },
    { e: "😟", n: "worried face" },
    { e: "🎁", n: "wrapped gift" },
    { e: "🔧", n: "wrench" },
    { e: "✍", n: "writing hand" },
    { e: "🧶", n: "yarn" },
    { e: "🥱", n: "yawning face" },
    { e: "🟡", n: "yellow circle" },
    { e: "💛", n: "yellow heart" },
    { e: "🟨", n: "yellow square" },
    { e: "💴", n: "yen banknote" },
    { e: "☯", n: "yin yang" },
    { e: "🪀", n: "yo-yo" },
    { e: "🤪", n: "zany face" },
    { e: "🦓", n: "zebra" },
    { e: "🤐", n: "zipper-mouth face" },
    { e: "🧟", n: "zombie" },
    { e: "💤", n: "zzz" }
];
