# ~/.config/hypr/hyprlock.conf

$font = FiraCode Nerd Font Mono Regular

general {
    hide_cursor = true
    immediate_render = false
    fail_timeout = 2000
}

auth {
    pam:enabled = true
}

animations {
    enabled = true
    bezier = easeOut, 0.16, 1, 0.3, 1
    animation = fadeIn, 1, 10, easeOut, slide top
    animation = fadeOut, 1, 10, easeOut
    animation = inputFieldFade, 1, 5, easeOut
    animation = inputFieldColors, 1, 7, easeOut
    animation = inputFieldWidth, 1, 6, easeOut
    animation = inputFieldDots, 1, 4, easeOut
}

background {
    monitor =
    path = ~/Pictures/View-of-Ornans-by-Gustave-Courbet.jpg
    blur_passes = 4
    blur_size = 8
    contrast = 0.9
    brightness = 0.8
    color = rgba(10, 10, 14, 1.0)
}

shape {
    monitor =
    size = 100%, 100%
    color = rgba(0, 0, 0, 0.35)
    zindex = -2
}

input-field {
    monitor =
    size = 28%, 6%
    outline_thickness = 3
    rounding = 18

    outer_color = rgb(0, 0, 0)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(220, 220, 220)

    check_color = rgb(0, 0, 0)
    fail_color = rgb(0, 0, 0)

    placeholder_text = <i>Enter password</i>
    fail_text = <b>Auth failed</b>

    dots_size = 0.35
    dots_spacing = 0.25
    dots_center = true

    font_family = $font

    position = 0, 0
    halign = center
    valign = center
}

# TIME (center)
label {
    monitor =
    text = $TIME12
    font_size = 90
    font_family = $font
    color = rgba(240, 240, 240, 1.0)

    position = 0, -200
    halign = center
    valign = top
}

# DATE (under time)
label {
    monitor =
    text = cmd[update:60000] date +"%A • %d %B %Y"
    font_size = 22
    font_family = $font
    color = rgba(180, 180, 180, 1.0)

    position = 0, -280
    halign = center
    valign = center
}
