general {
    lock_cmd = /home/josh/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 180
    on-timeout = /home/josh/.config/hypr/scripts/lock.sh
}
