$font = FiraCode Nerd Font Mono
$background = ~/Pictures/Road-to-Samarkand.png

background {
    monitor =
    path = $background
    blur_passes = 3
    contrast = 0.8
    brightness = 0.5
    vignette = 0.5
    vignette_opacity = 0.3
    crossfade_time = 0.5
}

# animations {
#     enabled = true
#     bezier = easeOut, 0.16, 1, 0.3, 1
#
#     animation = fadeIn, 1, 10, easeOut, slide top
#     animation = fadeOut, 1, 10, easeOut
#
#     animation = inputFieldFade, 1, 18, easeInOut
#     animation = inputFieldColors, 1, 8, easeOut
#     animation = inputFieldWidth, 1, 14, easeOut
#     animation = inputFieldDots, 1, 8, easeOut
# }

auth {
    pam:enabled = true
}

label {
    monitor =
    text = cmd[update:1000] date +"%I"
    font_size = 90
    font_family = $font
    color = rgba(255, 255, 255, 0.9)

    position = 0, 230
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%M"
    font_size = 90
    font_family = $font
    color = rgba(255, 255, 255, 0.9)

    position = 0, 110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A • %d %B %Y"
    font_size = 22
    font_family = $font
    color = rgba(255, 255, 255, 0.6)

    position = 0, 20
    halign = center
    valign = center
}

image {
    monitor =

    path = ~/Pictures/profile.jpg

    size = 130
    rounding = -1
    border_size = 4
    border_color = rgb(0, 0, 0)
    position = 0, 160
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 210, 40
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgba(37, 37, 48, 0.90)
    inner_color = rgba(20, 20, 21, 0.85)
    font_color  = rgba(205, 205, 205, 1.0)

    check_color = rgba(127, 165, 99, 1.0)
    fail_color  = rgba(216, 100, 126, 1.0)

    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff99">Enter Password...</span>
    hide_input = false
    position = 0, 100
    halign = center
    valign = bottom
}

general {
    no_fade_in = true
    grace = 0
    disable_loading = true
}
