# ~/.config/hypr/hyprlock.conf

$font = FiraCode Nerd Font Mono Regular
$background = ~/Pictures/Road-to-Samarkand.png

general {
    hide_cursor = true
    immediate_render = false
    fail_timeout = 2000
}

auth {
    pam:enabled = true
}

animations {
    enabled = true
    bezier = easeOut, 0.16, 1, 0.3, 1

    animation = fadeIn, 1, 10, easeOut, slide top
    animation = fadeOut, 1, 10, easeOut

    animation = inputFieldFade, 1, 18, easeInOut
    animation = inputFieldColors, 1, 8, easeOut
    animation = inputFieldWidth, 1, 14, easeOut
    animation = inputFieldDots, 1, 8, easeOut
}

background {
    monitor =
    path = $background
    blur_passes = 4
    blur_size = 8
    contrast = 0.9
    brightness = 0.8
    color = rgba(20, 20, 21, 0.85)
}

shape {
    monitor =
    size = 100%, 100%
    color = rgba(37, 37, 48, 0.35)
    zindex = -2
}

input-field {
    monitor =
    size = 28%, 6%
    outline_thickness = 3
    rounding = 18

    outer_color = rgba(37, 37, 48, 0.90)
    inner_color = rgba(20, 20, 21, 0.85)
    font_color  = rgba(205, 205, 205, 1.0)

    check_color = rgba(127, 165, 99, 1.0)
    fail_color  = rgba(216, 100, 126, 1.0)

    placeholder_text = <i>Enter password</i>
    fail_text = <b>Auth failed</b>

    dots_size = 0.35
    dots_spacing = 0.25
    dots_center = true

    font_family = $font

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12
    font_size = 90
    font_family = $font
    color = rgba(205, 205, 205, 1.0)

    position = 0, -200
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A • %d %B %Y"
    font_size = 22
    font_family = $font
    color = rgba(174, 174, 209, 1.0)

    position = 0, -350
    offset = 0, 110
    halign = center
    valign = top
}
